#pragma line 1 "resource/lab3/dct.c" ::: 0
#pragma line 1 "resource/lab3/dct.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 148 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 283 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 421 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 191
#pragma line 7 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "resource/lab3/dct.c" 2 ::: 195
#pragma line 1 "resource/lab3/dct.h" 1 ::: 197
#pragma line 3 "resource/lab3/dct.c" 2 ::: 212
#pragma line 1 "resource/lab3/dct_coeff_table.txt" 1 ::: 220
#pragma line 10 "resource/lab3/dct.c" 2 ::: 229
