// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_1d2_HH_
#define _dct_1d2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_mul_mul_16s_1jbC.h"
#include "dct_mac_muladd_16kbM.h"
#include "dct_mac_muladd_16lbW.h"
#include "dct_mac_muladd_16mb6.h"
#include "dct_1d2_dct_coeffbkb.h"
#include "dct_1d2_dct_coeffcud.h"
#include "dct_1d2_dct_coeffdEe.h"
#include "dct_1d2_dct_coeffeOg.h"
#include "dct_1d2_dct_coefffYi.h"
#include "dct_1d2_dct_coeffg8j.h"
#include "dct_1d2_dct_coeffhbi.h"
#include "dct_1d2_dct_coeffibs.h"

namespace ap_rtl {

struct dct_1d2 : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > src_address0;
    sc_out< sc_logic > src_ce0;
    sc_in< sc_lv<16> > src_q0;
    sc_out< sc_lv<6> > src_address1;
    sc_out< sc_logic > src_ce1;
    sc_in< sc_lv<16> > src_q1;
    sc_in< sc_lv<4> > i_2;
    sc_out< sc_lv<6> > dst_address0;
    sc_out< sc_logic > dst_ce0;
    sc_out< sc_logic > dst_we0;
    sc_out< sc_lv<16> > dst_d0;
    sc_in< sc_lv<4> > i_21;


    // Module declarations
    dct_1d2(sc_module_name name);
    SC_HAS_PROCESS(dct_1d2);

    ~dct_1d2();

    sc_trace_file* mVcdFile;

    dct_1d2_dct_coeffbkb* dct_coeff_table_0_U;
    dct_1d2_dct_coeffcud* dct_coeff_table_1_U;
    dct_1d2_dct_coeffdEe* dct_coeff_table_2_U;
    dct_1d2_dct_coeffeOg* dct_coeff_table_3_U;
    dct_1d2_dct_coefffYi* dct_coeff_table_4_U;
    dct_1d2_dct_coeffg8j* dct_coeff_table_5_U;
    dct_1d2_dct_coeffhbi* dct_coeff_table_6_U;
    dct_1d2_dct_coeffibs* dct_coeff_table_7_U;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U0;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U1;
    dct_mac_muladd_16kbM<1,1,16,14,29,29>* dct_mac_muladd_16kbM_U2;
    dct_mul_mul_16s_1jbC<1,1,16,15,29>* dct_mul_mul_16s_1jbC_U3;
    dct_mac_muladd_16lbW<1,1,16,15,29,29>* dct_mac_muladd_16lbW_U4;
    dct_mac_muladd_16lbW<1,1,16,15,29,29>* dct_mac_muladd_16lbW_U5;
    dct_mac_muladd_16lbW<1,1,16,15,29,29>* dct_mac_muladd_16lbW_U6;
    dct_mac_muladd_16mb6<1,1,16,15,14,29>* dct_mac_muladd_16mb6_U7;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > dct_coeff_table_0_address0;
    sc_signal< sc_logic > dct_coeff_table_0_ce0;
    sc_signal< sc_lv<14> > dct_coeff_table_0_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_1_address0;
    sc_signal< sc_logic > dct_coeff_table_1_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_1_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_2_address0;
    sc_signal< sc_logic > dct_coeff_table_2_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_2_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_3_address0;
    sc_signal< sc_logic > dct_coeff_table_3_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_3_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_4_address0;
    sc_signal< sc_logic > dct_coeff_table_4_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_4_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_5_address0;
    sc_signal< sc_logic > dct_coeff_table_5_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_5_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_6_address0;
    sc_signal< sc_logic > dct_coeff_table_6_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_6_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_7_address0;
    sc_signal< sc_logic > dct_coeff_table_7_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_7_q0;
    sc_signal< sc_lv<4> > k_reg_267;
    sc_signal< sc_lv<16> > reg_278;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_reg_628;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage2;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage3;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<16> > reg_282;
    sc_signal< sc_lv<8> > tmp_18_cast_fu_294_p1;
    sc_signal< sc_lv<8> > tmp_18_cast_reg_583;
    sc_signal< sc_lv<6> > src_addr_reg_588;
    sc_signal< sc_lv<6> > src_addr_1_reg_593;
    sc_signal< sc_lv<6> > src_addr_2_reg_598;
    sc_signal< sc_lv<6> > src_addr_3_reg_603;
    sc_signal< sc_lv<6> > src_addr_4_reg_608;
    sc_signal< sc_lv<6> > src_addr_5_reg_613;
    sc_signal< sc_lv<6> > src_addr_6_reg_618;
    sc_signal< sc_lv<6> > src_addr_7_reg_623;
    sc_signal< sc_lv<1> > tmp_fu_416_p2;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter1_tmp_reg_628;
    sc_signal< sc_lv<4> > k_1_fu_422_p2;
    sc_signal< sc_lv<4> > k_1_reg_632;
    sc_signal< sc_lv<32> > k_cast8_fu_428_p1;
    sc_signal< sc_lv<32> > k_cast8_reg_637;
    sc_signal< sc_lv<8> > tmp_30_fu_438_p2;
    sc_signal< sc_lv<8> > tmp_30_reg_647;
    sc_signal< sc_lv<8> > ap_pipeline_reg_pp0_iter1_tmp_30_reg_647;
    sc_signal< sc_lv<15> > dct_coeff_table_1_lo_reg_667;
    sc_signal< sc_lv<15> > dct_coeff_table_3_lo_reg_672;
    sc_signal< sc_lv<14> > dct_coeff_table_0_lo_reg_682;
    sc_signal< sc_lv<29> > tmp_7_1_fu_527_p2;
    sc_signal< sc_lv<29> > tmp_7_1_reg_687;
    sc_signal< sc_lv<29> > tmp_7_3_fu_533_p2;
    sc_signal< sc_lv<29> > tmp_7_3_reg_697;
    sc_signal< sc_lv<15> > dct_coeff_table_5_lo_reg_707;
    sc_signal< sc_lv<15> > dct_coeff_table_2_lo_reg_722;
    sc_signal< sc_lv<15> > dct_coeff_table_4_lo_reg_727;
    sc_signal< sc_lv<29> > tmp_7_5_fu_546_p2;
    sc_signal< sc_lv<29> > tmp_7_5_reg_732;
    sc_signal< sc_lv<15> > dct_coeff_table_6_lo_reg_737;
    sc_signal< sc_lv<15> > dct_coeff_table_7_lo_reg_742;
    sc_signal< sc_lv<29> > grp_fu_539_p3;
    sc_signal< sc_lv<29> > tmp2_reg_747;
    sc_signal< sc_lv<29> > tmp1_fu_485_p2;
    sc_signal< sc_lv<29> > tmp1_reg_752;
    sc_signal< sc_lv<29> > grp_fu_560_p3;
    sc_signal< sc_lv<29> > tmp5_reg_757;
    sc_signal< sc_lv<29> > grp_fu_567_p3;
    sc_signal< sc_lv<29> > tmp6_reg_762;
    sc_signal< sc_lv<4> > k_phi_fu_271_p4;
    sc_signal< sc_lv<32> > tmp_15_fu_306_p1;
    sc_signal< sc_lv<32> > tmp_17_fu_317_p3;
    sc_signal< sc_lv<32> > tmp_19_fu_332_p3;
    sc_signal< sc_lv<32> > tmp_21_fu_347_p3;
    sc_signal< sc_lv<32> > tmp_23_fu_362_p3;
    sc_signal< sc_lv<32> > tmp_25_fu_377_p3;
    sc_signal< sc_lv<32> > tmp_27_fu_392_p3;
    sc_signal< sc_lv<32> > tmp_29_fu_407_p3;
    sc_signal< sc_lv<32> > tmp_35_cast_fu_503_p1;
    sc_signal< sc_lv<7> > tmp_13_fu_286_p3;
    sc_signal< sc_lv<7> > tmp_14_fu_298_p3;
    sc_signal< sc_lv<7> > tmp_16_fu_311_p2;
    sc_signal< sc_lv<7> > tmp_18_fu_326_p2;
    sc_signal< sc_lv<7> > tmp_20_fu_341_p2;
    sc_signal< sc_lv<7> > tmp_22_fu_356_p2;
    sc_signal< sc_lv<7> > tmp_24_fu_371_p2;
    sc_signal< sc_lv<7> > tmp_26_fu_386_p2;
    sc_signal< sc_lv<7> > tmp_28_fu_401_p2;
    sc_signal< sc_lv<8> > k_cast8_cast_fu_434_p1;
    sc_signal< sc_lv<29> > grp_fu_552_p3;
    sc_signal< sc_lv<29> > tmp4_fu_507_p2;
    sc_signal< sc_lv<29> > tmp_3_fu_511_p2;
    sc_signal< sc_lv<14> > grp_fu_539_p1;
    sc_signal< sc_lv<29> > grp_fu_574_p3;
    sc_signal< sc_lv<14> > grp_fu_574_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_lv<29> > grp_fu_539_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage0;
    static const sc_lv<6> ap_ST_fsm_pp0_stage1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage2;
    static const sc_lv<6> ap_ST_fsm_pp0_stage3;
    static const sc_lv<6> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<25> ap_const_lv25_0;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<7> ap_const_lv7_3;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<7> ap_const_lv7_5;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<29> ap_const_lv29_1000;
    static const sc_lv<32> ap_const_lv32_5;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dct_coeff_table_0_address0();
    void thread_dct_coeff_table_0_ce0();
    void thread_dct_coeff_table_1_address0();
    void thread_dct_coeff_table_1_ce0();
    void thread_dct_coeff_table_2_address0();
    void thread_dct_coeff_table_2_ce0();
    void thread_dct_coeff_table_3_address0();
    void thread_dct_coeff_table_3_ce0();
    void thread_dct_coeff_table_4_address0();
    void thread_dct_coeff_table_4_ce0();
    void thread_dct_coeff_table_5_address0();
    void thread_dct_coeff_table_5_ce0();
    void thread_dct_coeff_table_6_address0();
    void thread_dct_coeff_table_6_ce0();
    void thread_dct_coeff_table_7_address0();
    void thread_dct_coeff_table_7_ce0();
    void thread_dst_address0();
    void thread_dst_ce0();
    void thread_dst_d0();
    void thread_dst_we0();
    void thread_grp_fu_539_p1();
    void thread_grp_fu_539_p10();
    void thread_grp_fu_574_p2();
    void thread_k_1_fu_422_p2();
    void thread_k_cast8_cast_fu_434_p1();
    void thread_k_cast8_fu_428_p1();
    void thread_k_phi_fu_271_p4();
    void thread_src_address0();
    void thread_src_address1();
    void thread_src_ce0();
    void thread_src_ce1();
    void thread_tmp1_fu_485_p2();
    void thread_tmp4_fu_507_p2();
    void thread_tmp_13_fu_286_p3();
    void thread_tmp_14_fu_298_p3();
    void thread_tmp_15_fu_306_p1();
    void thread_tmp_16_fu_311_p2();
    void thread_tmp_17_fu_317_p3();
    void thread_tmp_18_cast_fu_294_p1();
    void thread_tmp_18_fu_326_p2();
    void thread_tmp_19_fu_332_p3();
    void thread_tmp_20_fu_341_p2();
    void thread_tmp_21_fu_347_p3();
    void thread_tmp_22_fu_356_p2();
    void thread_tmp_23_fu_362_p3();
    void thread_tmp_24_fu_371_p2();
    void thread_tmp_25_fu_377_p3();
    void thread_tmp_26_fu_386_p2();
    void thread_tmp_27_fu_392_p3();
    void thread_tmp_28_fu_401_p2();
    void thread_tmp_29_fu_407_p3();
    void thread_tmp_30_fu_438_p2();
    void thread_tmp_35_cast_fu_503_p1();
    void thread_tmp_3_fu_511_p2();
    void thread_tmp_fu_416_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
