// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct,hls_ip_2016_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=875,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=8,HLS_SYN_FF=678,HLS_SYN_LUT=518}" *)

module dct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 6'b1;
parameter    ap_ST_fsm_pp0_stage0 = 6'b10;
parameter    ap_ST_fsm_state4 = 6'b100;
parameter    ap_ST_fsm_state5 = 6'b1000;
parameter    ap_ST_fsm_pp1_stage0 = 6'b10000;
parameter    ap_ST_fsm_state8 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_5 = 32'b101;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [6:0] indvar_flatten_reg_130;
reg   [3:0] r_i_reg_141;
reg   [3:0] c_i_reg_152;
reg   [6:0] indvar_flatten2_reg_163;
reg   [3:0] r_i2_reg_174;
reg   [3:0] c_i5_reg_185;
wire   [0:0] exitcond_flatten_fu_218_p2;
reg   [0:0] exitcond_flatten_reg_415;
wire   [0:0] ap_CS_fsm_pp0_stage0;
wire   [6:0] indvar_flatten_next_fu_224_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] c_i_mid2_fu_242_p3;
reg   [3:0] c_i_mid2_reg_424;
wire   [3:0] r_i_cast8_mid2_v_fu_250_p3;
reg   [3:0] r_i_cast8_mid2_v_reg_429;
wire   [3:0] c_fu_285_p2;
wire   [0:0] exitcond_flatten2_fu_316_p2;
reg   [0:0] exitcond_flatten2_reg_445;
wire   [0:0] ap_CS_fsm_pp1_stage0;
wire   [6:0] indvar_flatten_next2_fu_322_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [3:0] r_i2_cast4_mid2_v_fu_348_p3;
reg   [3:0] r_i2_cast4_mid2_v_reg_454;
wire   [5:0] sum3_i_fu_399_p2;
reg   [5:0] sum3_i_reg_464;
wire   [3:0] c_1_fu_405_p2;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] ap_CS_fsm_state5;
wire    grp_dct_2d_fu_196_ap_done;
reg    ap_enable_reg_pp1_iter1;
reg   [5:0] buf_2d_in_address0;
reg    buf_2d_in_ce0;
reg    buf_2d_in_we0;
wire   [15:0] buf_2d_in_q0;
reg    buf_2d_in_ce1;
wire   [15:0] buf_2d_in_q1;
reg   [5:0] buf_2d_out_address0;
reg    buf_2d_out_ce0;
reg    buf_2d_out_we0;
wire   [15:0] buf_2d_out_q0;
wire    grp_dct_2d_fu_196_ap_start;
wire    grp_dct_2d_fu_196_ap_idle;
wire    grp_dct_2d_fu_196_ap_ready;
wire   [5:0] grp_dct_2d_fu_196_in_block_address0;
wire    grp_dct_2d_fu_196_in_block_ce0;
wire   [5:0] grp_dct_2d_fu_196_in_block_address1;
wire    grp_dct_2d_fu_196_in_block_ce1;
wire   [5:0] grp_dct_2d_fu_196_out_block_address0;
wire    grp_dct_2d_fu_196_out_block_ce0;
wire    grp_dct_2d_fu_196_out_block_we0;
wire   [15:0] grp_dct_2d_fu_196_out_block_d0;
reg   [3:0] r_i_phi_fu_145_p4;
reg   [3:0] r_i2_phi_fu_178_p4;
reg    ap_reg_grp_dct_2d_fu_196_ap_start;
wire   [0:0] ap_CS_fsm_state4;
wire   [31:0] sum_i_cast_fu_280_p1;
wire   [31:0] tmp_38_cast_fu_311_p1;
wire   [31:0] tmp_42_cast_fu_394_p1;
wire   [31:0] sum3_i_cast_fu_411_p1;
wire   [0:0] exitcond_i_fu_236_p2;
wire   [3:0] r_fu_230_p2;
wire   [2:0] tmp_1_fu_258_p1;
wire   [5:0] tmp_i_mid2_fu_262_p3;
wire   [5:0] c_i_cast6_fu_270_p1;
wire   [5:0] sum_i_fu_274_p2;
wire   [6:0] tmp_fu_291_p3;
wire   [7:0] tmp_36_cast_fu_298_p1;
wire   [7:0] c_i_cast5_cast_fu_302_p1;
wire   [7:0] tmp_s_fu_305_p2;
wire   [0:0] exitcond_i1_fu_334_p2;
wire   [3:0] r_1_fu_328_p2;
wire   [6:0] tmp_31_fu_356_p3;
wire   [2:0] tmp_2_fu_368_p1;
wire   [3:0] c_i5_mid2_fu_340_p3;
wire   [7:0] tmp_40_cast_fu_364_p1;
wire   [7:0] c_i5_cast1_cast_fu_384_p1;
wire   [7:0] tmp_32_fu_388_p2;
wire   [5:0] tmp_i4_mid2_fu_372_p3;
wire   [5:0] c_i5_cast2_fu_380_p1;
wire   [0:0] ap_CS_fsm_state8;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'b1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_reg_grp_dct_2d_fu_196_ap_start = 1'b0;
end

dct_2d_col_inbuf #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_in_address0),
    .ce0(buf_2d_in_ce0),
    .we0(buf_2d_in_we0),
    .d0(input_r_q0),
    .q0(buf_2d_in_q0),
    .address1(grp_dct_2d_fu_196_in_block_address1),
    .ce1(buf_2d_in_ce1),
    .q1(buf_2d_in_q1)
);

dct_2d_row_outbuf #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_out_address0),
    .ce0(buf_2d_out_ce0),
    .we0(buf_2d_out_we0),
    .d0(grp_dct_2d_fu_196_out_block_d0),
    .q0(buf_2d_out_q0)
);

dct_2d grp_dct_2d_fu_196(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_2d_fu_196_ap_start),
    .ap_done(grp_dct_2d_fu_196_ap_done),
    .ap_idle(grp_dct_2d_fu_196_ap_idle),
    .ap_ready(grp_dct_2d_fu_196_ap_ready),
    .in_block_address0(grp_dct_2d_fu_196_in_block_address0),
    .in_block_ce0(grp_dct_2d_fu_196_in_block_ce0),
    .in_block_q0(buf_2d_in_q0),
    .in_block_address1(grp_dct_2d_fu_196_in_block_address1),
    .in_block_ce1(grp_dct_2d_fu_196_in_block_ce1),
    .in_block_q1(buf_2d_in_q1),
    .out_block_address0(grp_dct_2d_fu_196_out_block_address0),
    .out_block_ce0(grp_dct_2d_fu_196_out_block_ce0),
    .out_block_we0(grp_dct_2d_fu_196_out_block_we0),
    .out_block_d0(grp_dct_2d_fu_196_out_block_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten_fu_218_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_218_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten_fu_218_p2 == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & ~(1'b0 == exitcond_flatten2_fu_316_p2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == grp_dct_2d_fu_196_ap_done))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == exitcond_flatten2_fu_316_p2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b1;
        end else if ((((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == grp_dct_2d_fu_196_ap_done)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & ~(1'b0 == exitcond_flatten2_fu_316_p2)))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dct_2d_fu_196_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_reg_grp_dct_2d_fu_196_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dct_2d_fu_196_ap_ready)) begin
            ap_reg_grp_dct_2d_fu_196_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b0 == exitcond_flatten2_fu_316_p2))) begin
        c_i5_reg_185 <= c_1_fu_405_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == grp_dct_2d_fu_196_ap_done))) begin
        c_i5_reg_185 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_218_p2 == 1'b0))) begin
        c_i_reg_152 <= c_fu_285_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        c_i_reg_152 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b0 == exitcond_flatten2_fu_316_p2))) begin
        indvar_flatten2_reg_163 <= indvar_flatten_next2_fu_322_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == grp_dct_2d_fu_196_ap_done))) begin
        indvar_flatten2_reg_163 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_218_p2 == 1'b0))) begin
        indvar_flatten_reg_130 <= indvar_flatten_next_fu_224_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_130 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b0 == exitcond_flatten2_reg_445))) begin
        r_i2_reg_174 <= r_i2_cast4_mid2_v_reg_454;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(1'b0 == grp_dct_2d_fu_196_ap_done))) begin
        r_i2_reg_174 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_415 == 1'b0))) begin
        r_i_reg_141 <= r_i_cast8_mid2_v_reg_429;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        r_i_reg_141 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_218_p2 == 1'b0))) begin
        c_i_mid2_reg_424 <= c_i_mid2_fu_242_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp1_stage0)) begin
        exitcond_flatten2_reg_445 <= exitcond_flatten2_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        exitcond_flatten_reg_415 <= exitcond_flatten_fu_218_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b0 == exitcond_flatten2_fu_316_p2))) begin
        r_i2_cast4_mid2_v_reg_454 <= r_i2_cast4_mid2_v_fu_348_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_218_p2 == 1'b0))) begin
        r_i_cast8_mid2_v_reg_429 <= r_i_cast8_mid2_v_fu_250_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == exitcond_flatten2_fu_316_p2))) begin
        sum3_i_reg_464 <= sum3_i_fu_399_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        buf_2d_in_address0 = tmp_38_cast_fu_311_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_address0 = grp_dct_2d_fu_196_in_block_address0;
    end else begin
        buf_2d_in_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        buf_2d_in_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_ce0 = grp_dct_2d_fu_196_in_block_ce0;
    end else begin
        buf_2d_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_ce1 = grp_dct_2d_fu_196_in_block_ce1;
    end else begin
        buf_2d_in_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_415 == 1'b0))) begin
        buf_2d_in_we0 = 1'b1;
    end else begin
        buf_2d_in_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0))) begin
        buf_2d_out_address0 = tmp_42_cast_fu_394_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_address0 = grp_dct_2d_fu_196_out_block_address0;
    end else begin
        buf_2d_out_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter0))) begin
        buf_2d_out_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_ce0 = grp_dct_2d_fu_196_out_block_ce0;
    end else begin
        buf_2d_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_out_we0 = grp_dct_2d_fu_196_out_block_we0;
    end else begin
        buf_2d_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b0 == exitcond_flatten2_reg_445))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b0 == exitcond_flatten2_reg_445))) begin
        r_i2_phi_fu_178_p4 = r_i2_cast4_mid2_v_reg_454;
    end else begin
        r_i2_phi_fu_178_p4 = r_i2_reg_174;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_415 == 1'b0))) begin
        r_i_phi_fu_145_p4 = r_i_cast8_mid2_v_reg_429;
    end else begin
        r_i_phi_fu_145_p4 = r_i_reg_141;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten_fu_218_p2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (~(1'b0 == grp_dct_2d_fu_196_ap_done)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b1 == ap_enable_reg_pp1_iter0) & ~(1'b0 == exitcond_flatten2_fu_316_p2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state5 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state8 = ap_CS_fsm[ap_const_lv32_5];

assign c_1_fu_405_p2 = (ap_const_lv4_1 + c_i5_mid2_fu_340_p3);

assign c_fu_285_p2 = (ap_const_lv4_1 + c_i_mid2_fu_242_p3);

assign c_i5_cast1_cast_fu_384_p1 = c_i5_mid2_fu_340_p3;

assign c_i5_cast2_fu_380_p1 = c_i5_mid2_fu_340_p3;

assign c_i5_mid2_fu_340_p3 = ((exitcond_i1_fu_334_p2[0:0] === 1'b1) ? ap_const_lv4_0 : c_i5_reg_185);

assign c_i_cast5_cast_fu_302_p1 = c_i_mid2_reg_424;

assign c_i_cast6_fu_270_p1 = c_i_mid2_fu_242_p3;

assign c_i_mid2_fu_242_p3 = ((exitcond_i_fu_236_p2[0:0] === 1'b1) ? ap_const_lv4_0 : c_i_reg_152);

assign exitcond_flatten2_fu_316_p2 = ((indvar_flatten2_reg_163 == ap_const_lv7_40) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_218_p2 = ((indvar_flatten_reg_130 == ap_const_lv7_40) ? 1'b1 : 1'b0);

assign exitcond_i1_fu_334_p2 = ((c_i5_reg_185 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond_i_fu_236_p2 = ((c_i_reg_152 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign grp_dct_2d_fu_196_ap_start = ap_reg_grp_dct_2d_fu_196_ap_start;

assign indvar_flatten_next2_fu_322_p2 = (indvar_flatten2_reg_163 + ap_const_lv7_1);

assign indvar_flatten_next_fu_224_p2 = (indvar_flatten_reg_130 + ap_const_lv7_1);

assign input_r_address0 = sum_i_cast_fu_280_p1;

assign output_r_address0 = sum3_i_cast_fu_411_p1;

assign output_r_d0 = buf_2d_out_q0;

assign r_1_fu_328_p2 = (ap_const_lv4_1 + r_i2_phi_fu_178_p4);

assign r_fu_230_p2 = (ap_const_lv4_1 + r_i_phi_fu_145_p4);

assign r_i2_cast4_mid2_v_fu_348_p3 = ((exitcond_i1_fu_334_p2[0:0] === 1'b1) ? r_1_fu_328_p2 : r_i2_phi_fu_178_p4);

assign r_i_cast8_mid2_v_fu_250_p3 = ((exitcond_i_fu_236_p2[0:0] === 1'b1) ? r_fu_230_p2 : r_i_phi_fu_145_p4);

assign sum3_i_cast_fu_411_p1 = sum3_i_reg_464;

assign sum3_i_fu_399_p2 = (tmp_i4_mid2_fu_372_p3 + c_i5_cast2_fu_380_p1);

assign sum_i_cast_fu_280_p1 = sum_i_fu_274_p2;

assign sum_i_fu_274_p2 = (tmp_i_mid2_fu_262_p3 + c_i_cast6_fu_270_p1);

assign tmp_1_fu_258_p1 = r_i_cast8_mid2_v_fu_250_p3[2:0];

assign tmp_2_fu_368_p1 = r_i2_cast4_mid2_v_fu_348_p3[2:0];

assign tmp_31_fu_356_p3 = {{r_i2_cast4_mid2_v_fu_348_p3}, {ap_const_lv3_0}};

assign tmp_32_fu_388_p2 = (tmp_40_cast_fu_364_p1 + c_i5_cast1_cast_fu_384_p1);

assign tmp_36_cast_fu_298_p1 = tmp_fu_291_p3;

assign tmp_38_cast_fu_311_p1 = tmp_s_fu_305_p2;

assign tmp_40_cast_fu_364_p1 = tmp_31_fu_356_p3;

assign tmp_42_cast_fu_394_p1 = tmp_32_fu_388_p2;

assign tmp_fu_291_p3 = {{r_i_cast8_mid2_v_reg_429}, {ap_const_lv3_0}};

assign tmp_i4_mid2_fu_372_p3 = {{tmp_2_fu_368_p1}, {ap_const_lv3_0}};

assign tmp_i_mid2_fu_262_p3 = {{tmp_1_fu_258_p1}, {ap_const_lv3_0}};

assign tmp_s_fu_305_p2 = (tmp_36_cast_fu_298_p1 + c_i_cast5_cast_fu_302_p1);

endmodule //dct
