#pragma line 1 "resource/lab3/dct.c" ::: -10
#pragma line 1 "resource/lab3/dct.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 148 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 283 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 421 "D:/Programs/Vivado/Vivado_HLS/2016.3/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 181
#pragma line 7 "<command line>" 2 ::: 183
#pragma line 1 "<built-in>" 2 ::: 184
#pragma line 1 "resource/lab3/dct.c" 2 ::: 185
#pragma line 1 "resource/lab3/dct.h" 1 ::: 187
#pragma line 3 "resource/lab3/dct.c" 2 ::: 202
#pragma line 1 "resource/lab3/dct_coeff_table.txt" 1 ::: 210
#pragma line 10 "resource/lab3/dct.c" 2 ::: 219
#pragma line 10 "resource/lab3/dct.c" ::: 222
#pragma line 13 "resource/lab3/dct.c" ::: 228
#pragma line 40 "resource/lab3/dct.c" ::: 258
#pragma line 51 "resource/lab3/dct.c" ::: 272
#pragma line 62 "resource/lab3/dct.c" ::: 286
#pragma line 74 "resource/lab3/dct.c" ::: 301
#pragma line 81 "resource/lab3/dct.c" ::: 311
