// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dct_2d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_2d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_2d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> dct_2d::ap_ST_fsm_state1 = "1";
const sc_lv<9> dct_2d::ap_ST_fsm_state2 = "10";
const sc_lv<9> dct_2d::ap_ST_fsm_state3 = "100";
const sc_lv<9> dct_2d::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<9> dct_2d::ap_ST_fsm_state6 = "10000";
const sc_lv<9> dct_2d::ap_ST_fsm_state7 = "100000";
const sc_lv<9> dct_2d::ap_ST_fsm_state8 = "1000000";
const sc_lv<9> dct_2d::ap_ST_fsm_pp1_stage0 = "10000000";
const sc_lv<9> dct_2d::ap_ST_fsm_state11 = "100000000";
const sc_lv<32> dct_2d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dct_2d::ap_const_lv1_1 = "1";
const sc_lv<32> dct_2d::ap_const_lv32_1 = "1";
const sc_lv<32> dct_2d::ap_const_lv32_3 = "11";
const sc_lv<1> dct_2d::ap_const_lv1_0 = "0";
const sc_lv<32> dct_2d::ap_const_lv32_5 = "101";
const sc_lv<32> dct_2d::ap_const_lv32_7 = "111";
const sc_lv<4> dct_2d::ap_const_lv4_0 = "0000";
const sc_lv<32> dct_2d::ap_const_lv32_2 = "10";
const sc_lv<7> dct_2d::ap_const_lv7_0 = "0000000";
const sc_lv<32> dct_2d::ap_const_lv32_6 = "110";
const sc_lv<32> dct_2d::ap_const_lv32_4 = "100";
const sc_lv<4> dct_2d::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_2d::ap_const_lv4_1 = "1";
const sc_lv<7> dct_2d::ap_const_lv7_40 = "1000000";
const sc_lv<7> dct_2d::ap_const_lv7_1 = "1";
const sc_lv<3> dct_2d::ap_const_lv3_0 = "000";
const sc_lv<32> dct_2d::ap_const_lv32_8 = "1000";

dct_2d::dct_2d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    row_outbuf_U = new dct_2d_row_outbuf("row_outbuf_U");
    row_outbuf_U->clk(ap_clk);
    row_outbuf_U->reset(ap_rst);
    row_outbuf_U->address0(row_outbuf_address0);
    row_outbuf_U->ce0(row_outbuf_ce0);
    row_outbuf_U->we0(row_outbuf_we0);
    row_outbuf_U->d0(grp_dct_1d2_fu_207_dst_d0);
    row_outbuf_U->q0(row_outbuf_q0);
    col_outbuf_U = new dct_2d_row_outbuf("col_outbuf_U");
    col_outbuf_U->clk(ap_clk);
    col_outbuf_U->reset(ap_rst);
    col_outbuf_U->address0(col_outbuf_address0);
    col_outbuf_U->ce0(col_outbuf_ce0);
    col_outbuf_U->we0(col_outbuf_we0);
    col_outbuf_U->d0(grp_dct_1d2_fu_207_dst_d0);
    col_outbuf_U->q0(col_outbuf_q0);
    col_inbuf_U = new dct_2d_row_outbuf("col_inbuf_U");
    col_inbuf_U->clk(ap_clk);
    col_inbuf_U->reset(ap_rst);
    col_inbuf_U->address0(col_inbuf_address0);
    col_inbuf_U->ce0(col_inbuf_ce0);
    col_inbuf_U->we0(col_inbuf_we0);
    col_inbuf_U->d0(row_outbuf_q0);
    col_inbuf_U->q0(col_inbuf_q0);
    grp_dct_1d2_fu_207 = new dct_1d2("grp_dct_1d2_fu_207");
    grp_dct_1d2_fu_207->ap_clk(ap_clk);
    grp_dct_1d2_fu_207->ap_rst(ap_rst);
    grp_dct_1d2_fu_207->ap_start(grp_dct_1d2_fu_207_ap_start);
    grp_dct_1d2_fu_207->ap_done(grp_dct_1d2_fu_207_ap_done);
    grp_dct_1d2_fu_207->ap_idle(grp_dct_1d2_fu_207_ap_idle);
    grp_dct_1d2_fu_207->ap_ready(grp_dct_1d2_fu_207_ap_ready);
    grp_dct_1d2_fu_207->src_address0(grp_dct_1d2_fu_207_src_address0);
    grp_dct_1d2_fu_207->src_ce0(grp_dct_1d2_fu_207_src_ce0);
    grp_dct_1d2_fu_207->src_q0(grp_dct_1d2_fu_207_src_q0);
    grp_dct_1d2_fu_207->i_2(grp_dct_1d2_fu_207_i_2);
    grp_dct_1d2_fu_207->dst_address0(grp_dct_1d2_fu_207_dst_address0);
    grp_dct_1d2_fu_207->dst_ce0(grp_dct_1d2_fu_207_dst_ce0);
    grp_dct_1d2_fu_207->dst_we0(grp_dct_1d2_fu_207_dst_we0);
    grp_dct_1d2_fu_207->dst_d0(grp_dct_1d2_fu_207_dst_d0);
    grp_dct_1d2_fu_207->i_21(grp_dct_1d2_fu_207_i_21);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_col_inbuf_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_dct_1d2_fu_207_src_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_10_cast_fu_327_p1 );

    SC_METHOD(thread_col_inbuf_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( grp_dct_1d2_fu_207_src_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_col_inbuf_we0);
    sensitive << ( exitcond_flatten_reg_451 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_col_outbuf_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( grp_dct_1d2_fu_207_dst_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_16_cast_fu_406_p1 );

    SC_METHOD(thread_col_outbuf_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( grp_dct_1d2_fu_207_dst_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_col_outbuf_we0);
    sensitive << ( grp_dct_1d2_fu_207_dst_we0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_exitcond_flatten1_fu_344_p2);
    sensitive << ( indvar_flatten1_reg_174 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_234_p2);
    sensitive << ( indvar_flatten_reg_129 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_dct_1d2_fu_207_ap_start);
    sensitive << ( ap_reg_grp_dct_1d2_fu_207_ap_start );

    SC_METHOD(thread_grp_dct_1d2_fu_207_i_2);
    sensitive << ( i_reg_117 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_2_reg_162 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_dct_1d2_fu_207_i_21);
    sensitive << ( i_reg_117 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_2_reg_162 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_dct_1d2_fu_207_src_q0);
    sensitive << ( in_block_q0 );
    sensitive << ( col_inbuf_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_i_1_cast4_cast_fu_318_p1);
    sensitive << ( i_1_mid2_reg_460 );

    SC_METHOD(thread_i_1_mid2_fu_258_p3);
    sensitive << ( i_1_reg_151 );
    sensitive << ( tmp_s_fu_252_p2 );

    SC_METHOD(thread_i_3_cast1_cast_fu_428_p1);
    sensitive << ( i_3_mid2_reg_499 );

    SC_METHOD(thread_i_3_mid2_fu_368_p3);
    sensitive << ( i_3_reg_196 );
    sensitive << ( tmp_4_fu_362_p2 );

    SC_METHOD(thread_i_4_fu_228_p2);
    sensitive << ( i_reg_117 );

    SC_METHOD(thread_i_5_fu_338_p2);
    sensitive << ( i_2_reg_162 );

    SC_METHOD(thread_i_6_fu_301_p2);
    sensitive << ( i_1_mid2_fu_258_p3 );

    SC_METHOD(thread_i_7_fu_411_p2);
    sensitive << ( i_3_mid2_fu_368_p3 );

    SC_METHOD(thread_in_block_address0);
    sensitive << ( grp_dct_1d2_fu_207_src_address0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_in_block_ce0);
    sensitive << ( grp_dct_1d2_fu_207_src_ce0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_indvar_flatten_next1_fu_350_p2);
    sensitive << ( indvar_flatten1_reg_174 );

    SC_METHOD(thread_indvar_flatten_next_fu_240_p2);
    sensitive << ( indvar_flatten_reg_129 );

    SC_METHOD(thread_j_1_cast2_mid2_cast_fu_384_p1);
    sensitive << ( j_1_cast2_mid2_v_fu_376_p3 );

    SC_METHOD(thread_j_1_cast2_mid2_v_fu_376_p3);
    sensitive << ( j_1_phi_fu_189_p4 );
    sensitive << ( tmp_4_fu_362_p2 );
    sensitive << ( j_3_fu_356_p2 );

    SC_METHOD(thread_j_1_phi_fu_189_p4);
    sensitive << ( j_1_reg_185 );
    sensitive << ( exitcond_flatten1_reg_490 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( j_1_cast2_mid2_v_reg_504 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_j_2_fu_246_p2);
    sensitive << ( j_phi_fu_144_p4 );

    SC_METHOD(thread_j_3_fu_356_p2);
    sensitive << ( j_1_phi_fu_189_p4 );

    SC_METHOD(thread_j_cast5_mid2_cast_fu_274_p1);
    sensitive << ( j_cast5_mid2_v_fu_266_p3 );

    SC_METHOD(thread_j_cast5_mid2_v_fu_266_p3);
    sensitive << ( j_phi_fu_144_p4 );
    sensitive << ( tmp_s_fu_252_p2 );
    sensitive << ( j_2_fu_246_p2 );

    SC_METHOD(thread_j_phi_fu_144_p4);
    sensitive << ( j_reg_140 );
    sensitive << ( exitcond_flatten_reg_451 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_cast5_mid2_v_reg_465 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_out_block_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( tmp_13_cast_fu_437_p1 );

    SC_METHOD(thread_out_block_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_out_block_d0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( col_outbuf_q0 );

    SC_METHOD(thread_out_block_we0);
    sensitive << ( exitcond_flatten1_reg_490 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_row_outbuf_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_dct_1d2_fu_207_dst_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_8_cast_fu_296_p1 );

    SC_METHOD(thread_row_outbuf_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_dct_1d2_fu_207_dst_ce0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_row_outbuf_we0);
    sensitive << ( grp_dct_1d2_fu_207_dst_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_10_cast_fu_327_p1);
    sensitive << ( tmp_2_fu_321_p2 );

    SC_METHOD(thread_tmp_10_fu_431_p2);
    sensitive << ( i_3_cast1_cast_fu_428_p1 );
    sensitive << ( tmp_12_cast_fu_424_p1 );

    SC_METHOD(thread_tmp_11_fu_388_p3);
    sensitive << ( i_3_mid2_fu_368_p3 );

    SC_METHOD(thread_tmp_12_cast_fu_424_p1);
    sensitive << ( tmp_6_fu_417_p3 );

    SC_METHOD(thread_tmp_12_fu_400_p2);
    sensitive << ( j_1_cast2_mid2_cast_fu_384_p1 );
    sensitive << ( tmp_15_cast_fu_396_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_437_p1);
    sensitive << ( tmp_10_fu_431_p2 );

    SC_METHOD(thread_tmp_15_cast_fu_396_p1);
    sensitive << ( tmp_11_fu_388_p3 );

    SC_METHOD(thread_tmp_16_cast_fu_406_p1);
    sensitive << ( tmp_12_fu_400_p2 );

    SC_METHOD(thread_tmp_1_fu_307_p3);
    sensitive << ( j_cast5_mid2_v_reg_465 );

    SC_METHOD(thread_tmp_2_fu_321_p2);
    sensitive << ( i_1_cast4_cast_fu_318_p1 );
    sensitive << ( tmp_4_cast_fu_314_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_314_p1);
    sensitive << ( tmp_1_fu_307_p3 );

    SC_METHOD(thread_tmp_4_fu_362_p2);
    sensitive << ( i_3_reg_196 );
    sensitive << ( exitcond_flatten1_fu_344_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_tmp_5_fu_278_p3);
    sensitive << ( i_1_mid2_fu_258_p3 );

    SC_METHOD(thread_tmp_6_cast_fu_286_p1);
    sensitive << ( tmp_5_fu_278_p3 );

    SC_METHOD(thread_tmp_6_fu_417_p3);
    sensitive << ( j_1_cast2_mid2_v_reg_504 );

    SC_METHOD(thread_tmp_8_cast_fu_296_p1);
    sensitive << ( tmp_8_fu_290_p2 );

    SC_METHOD(thread_tmp_8_fu_290_p2);
    sensitive << ( j_cast5_mid2_cast_fu_274_p1 );
    sensitive << ( tmp_6_cast_fu_286_p1 );

    SC_METHOD(thread_tmp_9_fu_332_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_2_reg_162 );

    SC_METHOD(thread_tmp_fu_222_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_117 );

    SC_METHOD(thread_tmp_s_fu_252_p2);
    sensitive << ( i_1_reg_151 );
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_222_p2 );
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_9_fu_332_p2 );
    sensitive << ( exitcond_flatten1_fu_344_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( grp_dct_1d2_fu_207_ap_done );

    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_reg_grp_dct_1d2_fu_207_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_2d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_block_address0, "(port)in_block_address0");
    sc_trace(mVcdFile, in_block_ce0, "(port)in_block_ce0");
    sc_trace(mVcdFile, in_block_q0, "(port)in_block_q0");
    sc_trace(mVcdFile, out_block_address0, "(port)out_block_address0");
    sc_trace(mVcdFile, out_block_ce0, "(port)out_block_ce0");
    sc_trace(mVcdFile, out_block_we0, "(port)out_block_we0");
    sc_trace(mVcdFile, out_block_d0, "(port)out_block_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_129, "indvar_flatten_reg_129");
    sc_trace(mVcdFile, j_reg_140, "j_reg_140");
    sc_trace(mVcdFile, i_1_reg_151, "i_1_reg_151");
    sc_trace(mVcdFile, indvar_flatten1_reg_174, "indvar_flatten1_reg_174");
    sc_trace(mVcdFile, j_1_reg_185, "j_1_reg_185");
    sc_trace(mVcdFile, i_3_reg_196, "i_3_reg_196");
    sc_trace(mVcdFile, tmp_fu_222_p2, "tmp_fu_222_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_4_fu_228_p2, "i_4_fu_228_p2");
    sc_trace(mVcdFile, i_4_reg_446, "i_4_reg_446");
    sc_trace(mVcdFile, exitcond_flatten_fu_234_p2, "exitcond_flatten_fu_234_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_451, "exitcond_flatten_reg_451");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, indvar_flatten_next_fu_240_p2, "indvar_flatten_next_fu_240_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, i_1_mid2_fu_258_p3, "i_1_mid2_fu_258_p3");
    sc_trace(mVcdFile, i_1_mid2_reg_460, "i_1_mid2_reg_460");
    sc_trace(mVcdFile, j_cast5_mid2_v_fu_266_p3, "j_cast5_mid2_v_fu_266_p3");
    sc_trace(mVcdFile, j_cast5_mid2_v_reg_465, "j_cast5_mid2_v_reg_465");
    sc_trace(mVcdFile, i_6_fu_301_p2, "i_6_fu_301_p2");
    sc_trace(mVcdFile, tmp_9_fu_332_p2, "tmp_9_fu_332_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_5_fu_338_p2, "i_5_fu_338_p2");
    sc_trace(mVcdFile, i_5_reg_485, "i_5_reg_485");
    sc_trace(mVcdFile, exitcond_flatten1_fu_344_p2, "exitcond_flatten1_fu_344_p2");
    sc_trace(mVcdFile, exitcond_flatten1_reg_490, "exitcond_flatten1_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_350_p2, "indvar_flatten_next1_fu_350_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, i_3_mid2_fu_368_p3, "i_3_mid2_fu_368_p3");
    sc_trace(mVcdFile, i_3_mid2_reg_499, "i_3_mid2_reg_499");
    sc_trace(mVcdFile, j_1_cast2_mid2_v_fu_376_p3, "j_1_cast2_mid2_v_fu_376_p3");
    sc_trace(mVcdFile, j_1_cast2_mid2_v_reg_504, "j_1_cast2_mid2_v_reg_504");
    sc_trace(mVcdFile, i_7_fu_411_p2, "i_7_fu_411_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, row_outbuf_address0, "row_outbuf_address0");
    sc_trace(mVcdFile, row_outbuf_ce0, "row_outbuf_ce0");
    sc_trace(mVcdFile, row_outbuf_we0, "row_outbuf_we0");
    sc_trace(mVcdFile, row_outbuf_q0, "row_outbuf_q0");
    sc_trace(mVcdFile, col_outbuf_address0, "col_outbuf_address0");
    sc_trace(mVcdFile, col_outbuf_ce0, "col_outbuf_ce0");
    sc_trace(mVcdFile, col_outbuf_we0, "col_outbuf_we0");
    sc_trace(mVcdFile, col_outbuf_q0, "col_outbuf_q0");
    sc_trace(mVcdFile, col_inbuf_address0, "col_inbuf_address0");
    sc_trace(mVcdFile, col_inbuf_ce0, "col_inbuf_ce0");
    sc_trace(mVcdFile, col_inbuf_we0, "col_inbuf_we0");
    sc_trace(mVcdFile, col_inbuf_q0, "col_inbuf_q0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_ap_start, "grp_dct_1d2_fu_207_ap_start");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_ap_done, "grp_dct_1d2_fu_207_ap_done");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_ap_idle, "grp_dct_1d2_fu_207_ap_idle");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_ap_ready, "grp_dct_1d2_fu_207_ap_ready");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_src_address0, "grp_dct_1d2_fu_207_src_address0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_src_ce0, "grp_dct_1d2_fu_207_src_ce0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_src_q0, "grp_dct_1d2_fu_207_src_q0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_i_2, "grp_dct_1d2_fu_207_i_2");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_dst_address0, "grp_dct_1d2_fu_207_dst_address0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_dst_ce0, "grp_dct_1d2_fu_207_dst_ce0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_dst_we0, "grp_dct_1d2_fu_207_dst_we0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_dst_d0, "grp_dct_1d2_fu_207_dst_d0");
    sc_trace(mVcdFile, grp_dct_1d2_fu_207_i_21, "grp_dct_1d2_fu_207_i_21");
    sc_trace(mVcdFile, i_reg_117, "i_reg_117");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, j_phi_fu_144_p4, "j_phi_fu_144_p4");
    sc_trace(mVcdFile, i_2_reg_162, "i_2_reg_162");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_1_phi_fu_189_p4, "j_1_phi_fu_189_p4");
    sc_trace(mVcdFile, ap_reg_grp_dct_1d2_fu_207_ap_start, "ap_reg_grp_dct_1d2_fu_207_ap_start");
    sc_trace(mVcdFile, tmp_8_cast_fu_296_p1, "tmp_8_cast_fu_296_p1");
    sc_trace(mVcdFile, tmp_10_cast_fu_327_p1, "tmp_10_cast_fu_327_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_406_p1, "tmp_16_cast_fu_406_p1");
    sc_trace(mVcdFile, tmp_13_cast_fu_437_p1, "tmp_13_cast_fu_437_p1");
    sc_trace(mVcdFile, tmp_s_fu_252_p2, "tmp_s_fu_252_p2");
    sc_trace(mVcdFile, j_2_fu_246_p2, "j_2_fu_246_p2");
    sc_trace(mVcdFile, tmp_5_fu_278_p3, "tmp_5_fu_278_p3");
    sc_trace(mVcdFile, j_cast5_mid2_cast_fu_274_p1, "j_cast5_mid2_cast_fu_274_p1");
    sc_trace(mVcdFile, tmp_6_cast_fu_286_p1, "tmp_6_cast_fu_286_p1");
    sc_trace(mVcdFile, tmp_8_fu_290_p2, "tmp_8_fu_290_p2");
    sc_trace(mVcdFile, tmp_1_fu_307_p3, "tmp_1_fu_307_p3");
    sc_trace(mVcdFile, i_1_cast4_cast_fu_318_p1, "i_1_cast4_cast_fu_318_p1");
    sc_trace(mVcdFile, tmp_4_cast_fu_314_p1, "tmp_4_cast_fu_314_p1");
    sc_trace(mVcdFile, tmp_2_fu_321_p2, "tmp_2_fu_321_p2");
    sc_trace(mVcdFile, tmp_4_fu_362_p2, "tmp_4_fu_362_p2");
    sc_trace(mVcdFile, j_3_fu_356_p2, "j_3_fu_356_p2");
    sc_trace(mVcdFile, tmp_11_fu_388_p3, "tmp_11_fu_388_p3");
    sc_trace(mVcdFile, j_1_cast2_mid2_cast_fu_384_p1, "j_1_cast2_mid2_cast_fu_384_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_396_p1, "tmp_15_cast_fu_396_p1");
    sc_trace(mVcdFile, tmp_12_fu_400_p2, "tmp_12_fu_400_p2");
    sc_trace(mVcdFile, tmp_6_fu_417_p3, "tmp_6_fu_417_p3");
    sc_trace(mVcdFile, i_3_cast1_cast_fu_428_p1, "i_3_cast1_cast_fu_428_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_424_p1, "tmp_12_cast_fu_424_p1");
    sc_trace(mVcdFile, tmp_10_fu_431_p2, "tmp_10_fu_431_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dct_2d::~dct_2d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete row_outbuf_U;
    delete col_outbuf_U;
    delete col_inbuf_U;
    delete grp_dct_1d2_fu_207;
}

void dct_2d::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                    !esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                     !esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0)))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read())))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_dct_1d2_fu_207_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
              esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0)) || 
             (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read())))) {
            ap_reg_grp_dct_1d2_fu_207_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_dct_1d2_fu_207_ap_ready.read())) {
            ap_reg_grp_dct_1d2_fu_207_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0))) {
        i_1_reg_151 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
        i_1_reg_151 = i_6_fu_301_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        i_2_reg_162 = ap_const_lv4_0;
    } else if ((!esl_seteq<1,1,1>(ap_const_logic_0, grp_dct_1d2_fu_207_ap_done.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        i_2_reg_162 = i_5_reg_485.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read()))) {
        i_3_reg_196 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
        i_3_reg_196 = i_7_fu_411_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_dct_1d2_fu_207_ap_done.read()))) {
        i_reg_117 = i_4_reg_446.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_117 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read()))) {
        indvar_flatten1_reg_174 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
        indvar_flatten1_reg_174 = indvar_flatten_next1_fu_350_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_129 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_129 = indvar_flatten_next_fu_240_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read()))) {
        j_1_reg_185 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_reg_490.read()))) {
        j_1_reg_185 = j_1_cast2_mid2_v_reg_504.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0))) {
        j_reg_140 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(exitcond_flatten_reg_451.read(), ap_const_lv1_0))) {
        j_reg_140 = j_cast5_mid2_v_reg_465.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()))) {
        exitcond_flatten1_reg_490 = exitcond_flatten1_fu_344_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()))) {
        exitcond_flatten_reg_451 = exitcond_flatten_fu_234_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
        i_1_mid2_reg_460 = i_1_mid2_fu_258_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
        i_3_mid2_reg_499 = i_3_mid2_fu_368_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        i_4_reg_446 = i_4_fu_228_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        i_5_reg_485 = i_5_fu_338_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
        j_1_cast2_mid2_v_reg_504 = j_1_cast2_mid2_v_fu_376_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
        j_cast5_mid2_v_reg_465 = j_cast5_mid2_v_fu_266_p3.read();
    }
}

void dct_2d::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(3, 3);
}

void dct_2d::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read().range(7, 7);
}

void dct_2d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void dct_2d::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(8, 8);
}

void dct_2d::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void dct_2d::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void dct_2d::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(4, 4);
}

void dct_2d::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(5, 5);
}

void dct_2d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(6, 6);
}

void dct_2d::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_2d::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_2d::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_2d::thread_col_inbuf_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        col_inbuf_address0 =  (sc_lv<6>) (tmp_10_cast_fu_327_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        col_inbuf_address0 = grp_dct_1d2_fu_207_src_address0.read();
    } else {
        col_inbuf_address0 = "XXXXXX";
    }
}

void dct_2d::thread_col_inbuf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        col_inbuf_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        col_inbuf_ce0 = grp_dct_1d2_fu_207_src_ce0.read();
    } else {
        col_inbuf_ce0 = ap_const_logic_0;
    }
}

void dct_2d::thread_col_inbuf_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_451.read(), ap_const_lv1_0)))) {
        col_inbuf_we0 = ap_const_logic_1;
    } else {
        col_inbuf_we0 = ap_const_logic_0;
    }
}

void dct_2d::thread_col_outbuf_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        col_outbuf_address0 =  (sc_lv<6>) (tmp_16_cast_fu_406_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        col_outbuf_address0 = grp_dct_1d2_fu_207_dst_address0.read();
    } else {
        col_outbuf_address0 = "XXXXXX";
    }
}

void dct_2d::thread_col_outbuf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        col_outbuf_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        col_outbuf_ce0 = grp_dct_1d2_fu_207_dst_ce0.read();
    } else {
        col_outbuf_ce0 = ap_const_logic_0;
    }
}

void dct_2d::thread_col_outbuf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        col_outbuf_we0 = grp_dct_1d2_fu_207_dst_we0.read();
    } else {
        col_outbuf_we0 = ap_const_logic_0;
    }
}

void dct_2d::thread_exitcond_flatten1_fu_344_p2() {
    exitcond_flatten1_fu_344_p2 = (!indvar_flatten1_reg_174.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten1_reg_174.read() == ap_const_lv7_40);
}

void dct_2d::thread_exitcond_flatten_fu_234_p2() {
    exitcond_flatten_fu_234_p2 = (!indvar_flatten_reg_129.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_129.read() == ap_const_lv7_40);
}

void dct_2d::thread_grp_dct_1d2_fu_207_ap_start() {
    grp_dct_1d2_fu_207_ap_start = ap_reg_grp_dct_1d2_fu_207_ap_start.read();
}

void dct_2d::thread_grp_dct_1d2_fu_207_i_2() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        grp_dct_1d2_fu_207_i_2 = i_2_reg_162.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        grp_dct_1d2_fu_207_i_2 = i_reg_117.read();
    } else {
        grp_dct_1d2_fu_207_i_2 =  (sc_lv<4>) ("XXXX");
    }
}

void dct_2d::thread_grp_dct_1d2_fu_207_i_21() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        grp_dct_1d2_fu_207_i_21 = i_2_reg_162.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        grp_dct_1d2_fu_207_i_21 = i_reg_117.read();
    } else {
        grp_dct_1d2_fu_207_i_21 =  (sc_lv<4>) ("XXXX");
    }
}

void dct_2d::thread_grp_dct_1d2_fu_207_src_q0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        grp_dct_1d2_fu_207_src_q0 = col_inbuf_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        grp_dct_1d2_fu_207_src_q0 = in_block_q0.read();
    } else {
        grp_dct_1d2_fu_207_src_q0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void dct_2d::thread_i_1_cast4_cast_fu_318_p1() {
    i_1_cast4_cast_fu_318_p1 = esl_zext<8,4>(i_1_mid2_reg_460.read());
}

void dct_2d::thread_i_1_mid2_fu_258_p3() {
    i_1_mid2_fu_258_p3 = (!tmp_s_fu_252_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_s_fu_252_p2.read()[0].to_bool())? ap_const_lv4_0: i_1_reg_151.read());
}

void dct_2d::thread_i_3_cast1_cast_fu_428_p1() {
    i_3_cast1_cast_fu_428_p1 = esl_zext<8,4>(i_3_mid2_reg_499.read());
}

void dct_2d::thread_i_3_mid2_fu_368_p3() {
    i_3_mid2_fu_368_p3 = (!tmp_4_fu_362_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_4_fu_362_p2.read()[0].to_bool())? ap_const_lv4_0: i_3_reg_196.read());
}

void dct_2d::thread_i_4_fu_228_p2() {
    i_4_fu_228_p2 = (!i_reg_117.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_117.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_i_5_fu_338_p2() {
    i_5_fu_338_p2 = (!i_2_reg_162.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_2_reg_162.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_i_6_fu_301_p2() {
    i_6_fu_301_p2 = (!i_1_mid2_fu_258_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_1_mid2_fu_258_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_i_7_fu_411_p2() {
    i_7_fu_411_p2 = (!i_3_mid2_fu_368_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_3_mid2_fu_368_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_in_block_address0() {
    in_block_address0 = grp_dct_1d2_fu_207_src_address0.read();
}

void dct_2d::thread_in_block_ce0() {
    in_block_ce0 = grp_dct_1d2_fu_207_src_ce0.read();
}

void dct_2d::thread_indvar_flatten_next1_fu_350_p2() {
    indvar_flatten_next1_fu_350_p2 = (!indvar_flatten1_reg_174.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten1_reg_174.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct_2d::thread_indvar_flatten_next_fu_240_p2() {
    indvar_flatten_next_fu_240_p2 = (!indvar_flatten_reg_129.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_reg_129.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dct_2d::thread_j_1_cast2_mid2_cast_fu_384_p1() {
    j_1_cast2_mid2_cast_fu_384_p1 = esl_zext<8,4>(j_1_cast2_mid2_v_fu_376_p3.read());
}

void dct_2d::thread_j_1_cast2_mid2_v_fu_376_p3() {
    j_1_cast2_mid2_v_fu_376_p3 = (!tmp_4_fu_362_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_4_fu_362_p2.read()[0].to_bool())? j_3_fu_356_p2.read(): j_1_phi_fu_189_p4.read());
}

void dct_2d::thread_j_1_phi_fu_189_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_reg_490.read()))) {
        j_1_phi_fu_189_p4 = j_1_cast2_mid2_v_reg_504.read();
    } else {
        j_1_phi_fu_189_p4 = j_1_reg_185.read();
    }
}

void dct_2d::thread_j_2_fu_246_p2() {
    j_2_fu_246_p2 = (!j_phi_fu_144_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_phi_fu_144_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_j_3_fu_356_p2() {
    j_3_fu_356_p2 = (!j_1_phi_fu_189_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_1_phi_fu_189_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_2d::thread_j_cast5_mid2_cast_fu_274_p1() {
    j_cast5_mid2_cast_fu_274_p1 = esl_zext<8,4>(j_cast5_mid2_v_fu_266_p3.read());
}

void dct_2d::thread_j_cast5_mid2_v_fu_266_p3() {
    j_cast5_mid2_v_fu_266_p3 = (!tmp_s_fu_252_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_s_fu_252_p2.read()[0].to_bool())? j_2_fu_246_p2.read(): j_phi_fu_144_p4.read());
}

void dct_2d::thread_j_phi_fu_144_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_451.read(), ap_const_lv1_0))) {
        j_phi_fu_144_p4 = j_cast5_mid2_v_reg_465.read();
    } else {
        j_phi_fu_144_p4 = j_reg_140.read();
    }
}

void dct_2d::thread_out_block_address0() {
    out_block_address0 =  (sc_lv<6>) (tmp_13_cast_fu_437_p1.read());
}

void dct_2d::thread_out_block_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        out_block_ce0 = ap_const_logic_1;
    } else {
        out_block_ce0 = ap_const_logic_0;
    }
}

void dct_2d::thread_out_block_d0() {
    out_block_d0 = col_outbuf_q0.read();
}

void dct_2d::thread_out_block_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_reg_490.read())))) {
        out_block_we0 = ap_const_logic_1;
    } else {
        out_block_we0 = ap_const_logic_0;
    }
}

void dct_2d::thread_row_outbuf_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        row_outbuf_address0 =  (sc_lv<6>) (tmp_8_cast_fu_296_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        row_outbuf_address0 = grp_dct_1d2_fu_207_dst_address0.read();
    } else {
        row_outbuf_address0 = "XXXXXX";
    }
}

void dct_2d::thread_row_outbuf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        row_outbuf_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        row_outbuf_ce0 = grp_dct_1d2_fu_207_dst_ce0.read();
    } else {
        row_outbuf_ce0 = ap_const_logic_0;
    }
}

void dct_2d::thread_row_outbuf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        row_outbuf_we0 = grp_dct_1d2_fu_207_dst_we0.read();
    } else {
        row_outbuf_we0 = ap_const_logic_0;
    }
}

void dct_2d::thread_tmp_10_cast_fu_327_p1() {
    tmp_10_cast_fu_327_p1 = esl_zext<32,8>(tmp_2_fu_321_p2.read());
}

void dct_2d::thread_tmp_10_fu_431_p2() {
    tmp_10_fu_431_p2 = (!i_3_cast1_cast_fu_428_p1.read().is_01() || !tmp_12_cast_fu_424_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(i_3_cast1_cast_fu_428_p1.read()) + sc_biguint<8>(tmp_12_cast_fu_424_p1.read()));
}

void dct_2d::thread_tmp_11_fu_388_p3() {
    tmp_11_fu_388_p3 = esl_concat<4,3>(i_3_mid2_fu_368_p3.read(), ap_const_lv3_0);
}

void dct_2d::thread_tmp_12_cast_fu_424_p1() {
    tmp_12_cast_fu_424_p1 = esl_zext<8,7>(tmp_6_fu_417_p3.read());
}

void dct_2d::thread_tmp_12_fu_400_p2() {
    tmp_12_fu_400_p2 = (!j_1_cast2_mid2_cast_fu_384_p1.read().is_01() || !tmp_15_cast_fu_396_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(j_1_cast2_mid2_cast_fu_384_p1.read()) + sc_biguint<8>(tmp_15_cast_fu_396_p1.read()));
}

void dct_2d::thread_tmp_13_cast_fu_437_p1() {
    tmp_13_cast_fu_437_p1 = esl_zext<32,8>(tmp_10_fu_431_p2.read());
}

void dct_2d::thread_tmp_15_cast_fu_396_p1() {
    tmp_15_cast_fu_396_p1 = esl_zext<8,7>(tmp_11_fu_388_p3.read());
}

void dct_2d::thread_tmp_16_cast_fu_406_p1() {
    tmp_16_cast_fu_406_p1 = esl_zext<32,8>(tmp_12_fu_400_p2.read());
}

void dct_2d::thread_tmp_1_fu_307_p3() {
    tmp_1_fu_307_p3 = esl_concat<4,3>(j_cast5_mid2_v_reg_465.read(), ap_const_lv3_0);
}

void dct_2d::thread_tmp_2_fu_321_p2() {
    tmp_2_fu_321_p2 = (!i_1_cast4_cast_fu_318_p1.read().is_01() || !tmp_4_cast_fu_314_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(i_1_cast4_cast_fu_318_p1.read()) + sc_biguint<8>(tmp_4_cast_fu_314_p1.read()));
}

void dct_2d::thread_tmp_4_cast_fu_314_p1() {
    tmp_4_cast_fu_314_p1 = esl_zext<8,7>(tmp_1_fu_307_p3.read());
}

void dct_2d::thread_tmp_4_fu_362_p2() {
    tmp_4_fu_362_p2 = (!i_3_reg_196.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_3_reg_196.read() == ap_const_lv4_8);
}

void dct_2d::thread_tmp_5_fu_278_p3() {
    tmp_5_fu_278_p3 = esl_concat<4,3>(i_1_mid2_fu_258_p3.read(), ap_const_lv3_0);
}

void dct_2d::thread_tmp_6_cast_fu_286_p1() {
    tmp_6_cast_fu_286_p1 = esl_zext<8,7>(tmp_5_fu_278_p3.read());
}

void dct_2d::thread_tmp_6_fu_417_p3() {
    tmp_6_fu_417_p3 = esl_concat<4,3>(j_1_cast2_mid2_v_reg_504.read(), ap_const_lv3_0);
}

void dct_2d::thread_tmp_8_cast_fu_296_p1() {
    tmp_8_cast_fu_296_p1 = esl_zext<32,8>(tmp_8_fu_290_p2.read());
}

void dct_2d::thread_tmp_8_fu_290_p2() {
    tmp_8_fu_290_p2 = (!j_cast5_mid2_cast_fu_274_p1.read().is_01() || !tmp_6_cast_fu_286_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(j_cast5_mid2_cast_fu_274_p1.read()) + sc_biguint<8>(tmp_6_cast_fu_286_p1.read()));
}

void dct_2d::thread_tmp_9_fu_332_p2() {
    tmp_9_fu_332_p2 = (!i_2_reg_162.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_162.read() == ap_const_lv4_8);
}

void dct_2d::thread_tmp_fu_222_p2() {
    tmp_fu_222_p2 = (!i_reg_117.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_117.read() == ap_const_lv4_8);
}

void dct_2d::thread_tmp_s_fu_252_p2() {
    tmp_s_fu_252_p2 = (!i_1_reg_151.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_151.read() == ap_const_lv4_8);
}

void dct_2d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(tmp_fu_222_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dct_1d2_fu_207_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_234_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_9_fu_332_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_dct_1d2_fu_207_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten1_fu_344_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

