// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dct_1d_1_HH_
#define _dct_1d_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dct_mux_83_16_1.h"
#include "dct_mul_mul_15s_1jbC.h"
#include "dct_mac_muladd_14kbM.h"
#include "dct_mac_muladd_15lbW.h"
#include "dct_mac_muladd_15mb6.h"
#include "dct_1d_1_dct_coefbkb.h"
#include "dct_1d_1_dct_coefcud.h"
#include "dct_1d_1_dct_coefdEe.h"
#include "dct_1d_1_dct_coefeOg.h"
#include "dct_1d_1_dct_coeffYi.h"
#include "dct_1d_1_dct_coefg8j.h"
#include "dct_1d_1_dct_coefhbi.h"
#include "dct_1d_1_dct_coefibs.h"

namespace ap_rtl {

struct dct_1d_1 : public sc_module {
    // Port declarations 60
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<3> > src_0_address0;
    sc_out< sc_logic > src_0_ce0;
    sc_in< sc_lv<16> > src_0_q0;
    sc_out< sc_lv<3> > src_0_address1;
    sc_out< sc_logic > src_0_ce1;
    sc_in< sc_lv<16> > src_0_q1;
    sc_out< sc_lv<3> > src_1_address0;
    sc_out< sc_logic > src_1_ce0;
    sc_in< sc_lv<16> > src_1_q0;
    sc_out< sc_lv<3> > src_1_address1;
    sc_out< sc_logic > src_1_ce1;
    sc_in< sc_lv<16> > src_1_q1;
    sc_out< sc_lv<3> > src_2_address0;
    sc_out< sc_logic > src_2_ce0;
    sc_in< sc_lv<16> > src_2_q0;
    sc_out< sc_lv<3> > src_2_address1;
    sc_out< sc_logic > src_2_ce1;
    sc_in< sc_lv<16> > src_2_q1;
    sc_out< sc_lv<3> > src_3_address0;
    sc_out< sc_logic > src_3_ce0;
    sc_in< sc_lv<16> > src_3_q0;
    sc_out< sc_lv<3> > src_3_address1;
    sc_out< sc_logic > src_3_ce1;
    sc_in< sc_lv<16> > src_3_q1;
    sc_out< sc_lv<3> > src_4_address0;
    sc_out< sc_logic > src_4_ce0;
    sc_in< sc_lv<16> > src_4_q0;
    sc_out< sc_lv<3> > src_4_address1;
    sc_out< sc_logic > src_4_ce1;
    sc_in< sc_lv<16> > src_4_q1;
    sc_out< sc_lv<3> > src_5_address0;
    sc_out< sc_logic > src_5_ce0;
    sc_in< sc_lv<16> > src_5_q0;
    sc_out< sc_lv<3> > src_5_address1;
    sc_out< sc_logic > src_5_ce1;
    sc_in< sc_lv<16> > src_5_q1;
    sc_out< sc_lv<3> > src_6_address0;
    sc_out< sc_logic > src_6_ce0;
    sc_in< sc_lv<16> > src_6_q0;
    sc_out< sc_lv<3> > src_6_address1;
    sc_out< sc_logic > src_6_ce1;
    sc_in< sc_lv<16> > src_6_q1;
    sc_out< sc_lv<3> > src_7_address0;
    sc_out< sc_logic > src_7_ce0;
    sc_in< sc_lv<16> > src_7_q0;
    sc_out< sc_lv<3> > src_7_address1;
    sc_out< sc_logic > src_7_ce1;
    sc_in< sc_lv<16> > src_7_q1;
    sc_in< sc_lv<4> > i_2_i;
    sc_out< sc_lv<6> > dst_address0;
    sc_out< sc_logic > dst_ce0;
    sc_out< sc_logic > dst_we0;
    sc_out< sc_lv<16> > dst_d0;
    sc_in< sc_lv<4> > i_2_i1;


    // Module declarations
    dct_1d_1(sc_module_name name);
    SC_HAS_PROCESS(dct_1d_1);

    ~dct_1d_1();

    sc_trace_file* mVcdFile;

    dct_1d_1_dct_coefbkb* dct_coeff_table_14_U;
    dct_1d_1_dct_coefcud* dct_coeff_table_13_U;
    dct_1d_1_dct_coefdEe* dct_coeff_table_12_U;
    dct_1d_1_dct_coefeOg* dct_coeff_table_11_U;
    dct_1d_1_dct_coeffYi* dct_coeff_table_10_U;
    dct_1d_1_dct_coefg8j* dct_coeff_table_9_U;
    dct_1d_1_dct_coefhbi* dct_coeff_table_8_U;
    dct_1d_1_dct_coefibs* dct_coeff_table_U;
    dct_mux_83_16_1<1,1,16,16,16,16,16,16,16,16,3,16>* dct_mux_83_16_1_U9;
    dct_mux_83_16_1<1,1,16,16,16,16,16,16,16,16,3,16>* dct_mux_83_16_1_U10;
    dct_mul_mul_15s_1jbC<1,1,15,16,29>* dct_mul_mul_15s_1jbC_U11;
    dct_mul_mul_15s_1jbC<1,1,15,16,29>* dct_mul_mul_15s_1jbC_U12;
    dct_mac_muladd_14kbM<1,1,14,16,29,29>* dct_mac_muladd_14kbM_U13;
    dct_mul_mul_15s_1jbC<1,1,15,16,29>* dct_mul_mul_15s_1jbC_U14;
    dct_mac_muladd_15lbW<1,1,15,16,29,29>* dct_mac_muladd_15lbW_U15;
    dct_mac_muladd_15lbW<1,1,15,16,29,29>* dct_mac_muladd_15lbW_U16;
    dct_mac_muladd_15lbW<1,1,15,16,29,29>* dct_mac_muladd_15lbW_U17;
    dct_mac_muladd_15mb6<1,1,15,16,14,29>* dct_mac_muladd_15mb6_U18;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > dct_coeff_table_14_address0;
    sc_signal< sc_logic > dct_coeff_table_14_ce0;
    sc_signal< sc_lv<14> > dct_coeff_table_14_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_13_address0;
    sc_signal< sc_logic > dct_coeff_table_13_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_13_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_12_address0;
    sc_signal< sc_logic > dct_coeff_table_12_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_12_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_11_address0;
    sc_signal< sc_logic > dct_coeff_table_11_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_11_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_10_address0;
    sc_signal< sc_logic > dct_coeff_table_10_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_10_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_9_address0;
    sc_signal< sc_logic > dct_coeff_table_9_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_9_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_8_address0;
    sc_signal< sc_logic > dct_coeff_table_8_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_8_q0;
    sc_signal< sc_lv<3> > dct_coeff_table_address0;
    sc_signal< sc_logic > dct_coeff_table_ce0;
    sc_signal< sc_lv<15> > dct_coeff_table_q0;
    sc_signal< sc_lv<4> > k_reg_782;
    sc_signal< sc_lv<16> > grp_fu_793_p10;
    sc_signal< sc_lv<16> > reg_835;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_reg_1357;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage2;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage3;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<16> > grp_fu_814_p10;
    sc_signal< sc_lv<16> > reg_839;
    sc_signal< sc_lv<8> > tmp_14_cast_fu_851_p1;
    sc_signal< sc_lv<8> > tmp_14_cast_reg_1026;
    sc_signal< sc_lv<3> > tmp_13_fu_855_p1;
    sc_signal< sc_lv<3> > tmp_13_reg_1031;
    sc_signal< sc_lv<1> > tmp_fu_859_p2;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter1_tmp_reg_1357;
    sc_signal< sc_lv<4> > k_1_fu_865_p2;
    sc_signal< sc_lv<4> > k_1_reg_1361;
    sc_signal< sc_lv<32> > k_cast1_fu_871_p1;
    sc_signal< sc_lv<32> > k_cast1_reg_1366;
    sc_signal< sc_lv<8> > tmp_14_fu_881_p2;
    sc_signal< sc_lv<8> > tmp_14_reg_1376;
    sc_signal< sc_lv<8> > ap_pipeline_reg_pp0_iter1_tmp_14_reg_1376;
    sc_signal< sc_lv<15> > dct_coeff_table_13_l_reg_1396;
    sc_signal< sc_lv<15> > dct_coeff_table_11_l_reg_1401;
    sc_signal< sc_lv<14> > dct_coeff_table_14_l_reg_1411;
    sc_signal< sc_lv<29> > tmp_3_1_fu_970_p2;
    sc_signal< sc_lv<29> > tmp_3_1_reg_1416;
    sc_signal< sc_lv<29> > tmp_3_3_fu_976_p2;
    sc_signal< sc_lv<29> > tmp_3_3_reg_1426;
    sc_signal< sc_lv<15> > dct_coeff_table_9_lo_reg_1436;
    sc_signal< sc_lv<15> > dct_coeff_table_12_l_reg_1451;
    sc_signal< sc_lv<15> > dct_coeff_table_10_l_reg_1456;
    sc_signal< sc_lv<29> > tmp_3_5_fu_989_p2;
    sc_signal< sc_lv<29> > tmp_3_5_reg_1461;
    sc_signal< sc_lv<15> > dct_coeff_table_8_lo_reg_1466;
    sc_signal< sc_lv<15> > dct_coeff_table_load_reg_1471;
    sc_signal< sc_lv<29> > grp_fu_982_p3;
    sc_signal< sc_lv<29> > tmp2_reg_1476;
    sc_signal< sc_lv<29> > tmp1_fu_928_p2;
    sc_signal< sc_lv<29> > tmp1_reg_1481;
    sc_signal< sc_lv<29> > grp_fu_1003_p3;
    sc_signal< sc_lv<29> > tmp5_reg_1486;
    sc_signal< sc_lv<29> > grp_fu_1010_p3;
    sc_signal< sc_lv<29> > tmp6_reg_1491;
    sc_signal< sc_lv<4> > k_phi_fu_786_p4;
    sc_signal< sc_lv<32> > tmp_15_cast_fu_946_p1;
    sc_signal< sc_lv<7> > tmp_12_fu_843_p3;
    sc_signal< sc_lv<8> > k_cast1_cast_fu_877_p1;
    sc_signal< sc_lv<29> > grp_fu_995_p3;
    sc_signal< sc_lv<29> > tmp4_fu_950_p2;
    sc_signal< sc_lv<29> > tmp_9_fu_954_p2;
    sc_signal< sc_lv<14> > grp_fu_982_p0;
    sc_signal< sc_lv<29> > grp_fu_1017_p3;
    sc_signal< sc_lv<14> > grp_fu_1017_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< sc_lv<29> > grp_fu_982_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage0;
    static const sc_lv<6> ap_ST_fsm_pp0_stage1;
    static const sc_lv<6> ap_ST_fsm_pp0_stage2;
    static const sc_lv<6> ap_ST_fsm_pp0_stage3;
    static const sc_lv<6> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<29> ap_const_lv29_1000;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dct_coeff_table_10_address0();
    void thread_dct_coeff_table_10_ce0();
    void thread_dct_coeff_table_11_address0();
    void thread_dct_coeff_table_11_ce0();
    void thread_dct_coeff_table_12_address0();
    void thread_dct_coeff_table_12_ce0();
    void thread_dct_coeff_table_13_address0();
    void thread_dct_coeff_table_13_ce0();
    void thread_dct_coeff_table_14_address0();
    void thread_dct_coeff_table_14_ce0();
    void thread_dct_coeff_table_8_address0();
    void thread_dct_coeff_table_8_ce0();
    void thread_dct_coeff_table_9_address0();
    void thread_dct_coeff_table_9_ce0();
    void thread_dct_coeff_table_address0();
    void thread_dct_coeff_table_ce0();
    void thread_dst_address0();
    void thread_dst_ce0();
    void thread_dst_d0();
    void thread_dst_we0();
    void thread_grp_fu_1017_p2();
    void thread_grp_fu_982_p0();
    void thread_grp_fu_982_p00();
    void thread_k_1_fu_865_p2();
    void thread_k_cast1_cast_fu_877_p1();
    void thread_k_cast1_fu_871_p1();
    void thread_k_phi_fu_786_p4();
    void thread_src_0_address0();
    void thread_src_0_address1();
    void thread_src_0_ce0();
    void thread_src_0_ce1();
    void thread_src_1_address0();
    void thread_src_1_address1();
    void thread_src_1_ce0();
    void thread_src_1_ce1();
    void thread_src_2_address0();
    void thread_src_2_address1();
    void thread_src_2_ce0();
    void thread_src_2_ce1();
    void thread_src_3_address0();
    void thread_src_3_address1();
    void thread_src_3_ce0();
    void thread_src_3_ce1();
    void thread_src_4_address0();
    void thread_src_4_address1();
    void thread_src_4_ce0();
    void thread_src_4_ce1();
    void thread_src_5_address0();
    void thread_src_5_address1();
    void thread_src_5_ce0();
    void thread_src_5_ce1();
    void thread_src_6_address0();
    void thread_src_6_address1();
    void thread_src_6_ce0();
    void thread_src_6_ce1();
    void thread_src_7_address0();
    void thread_src_7_address1();
    void thread_src_7_ce0();
    void thread_src_7_ce1();
    void thread_tmp1_fu_928_p2();
    void thread_tmp4_fu_950_p2();
    void thread_tmp_12_fu_843_p3();
    void thread_tmp_13_fu_855_p1();
    void thread_tmp_14_cast_fu_851_p1();
    void thread_tmp_14_fu_881_p2();
    void thread_tmp_15_cast_fu_946_p1();
    void thread_tmp_9_fu_954_p2();
    void thread_tmp_fu_859_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
