-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.3
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dct,hls_ip_2016_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.400000,HLS_SYN_LAT=875,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=8,HLS_SYN_FF=678,HLS_SYN_LUT=518}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten_reg_130 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_i_reg_141 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_i_reg_152 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten2_reg_163 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_i2_reg_174 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_i5_reg_185 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal indvar_flatten_next_fu_224_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal c_i_mid2_fu_242_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_i_mid2_reg_424 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_i_cast8_mid2_v_fu_250_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_i_cast8_mid2_v_reg_429 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_fu_285_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten2_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten2_reg_445 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal indvar_flatten_next2_fu_322_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal r_i2_cast4_mid2_v_fu_348_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_i2_cast4_mid2_v_reg_454 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum3_i_fu_399_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sum3_i_reg_464 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_1_fu_405_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dct_2d_fu_196_ap_done : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_in_ce0 : STD_LOGIC;
    signal buf_2d_in_we0 : STD_LOGIC;
    signal buf_2d_in_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce1 : STD_LOGIC;
    signal buf_2d_in_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_out_ce0 : STD_LOGIC;
    signal buf_2d_out_we0 : STD_LOGIC;
    signal buf_2d_out_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_2d_fu_196_ap_start : STD_LOGIC;
    signal grp_dct_2d_fu_196_ap_idle : STD_LOGIC;
    signal grp_dct_2d_fu_196_ap_ready : STD_LOGIC;
    signal grp_dct_2d_fu_196_in_block_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_196_in_block_ce0 : STD_LOGIC;
    signal grp_dct_2d_fu_196_in_block_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_196_in_block_ce1 : STD_LOGIC;
    signal grp_dct_2d_fu_196_out_block_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_2d_fu_196_out_block_ce0 : STD_LOGIC;
    signal grp_dct_2d_fu_196_out_block_we0 : STD_LOGIC;
    signal grp_dct_2d_fu_196_out_block_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_i_phi_fu_145_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_i2_phi_fu_178_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_reg_grp_dct_2d_fu_196_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sum_i_cast_fu_280_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_38_cast_fu_311_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_42_cast_fu_394_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum3_i_cast_fu_411_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond_i_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_230_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_fu_258_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_i_mid2_fu_262_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_i_cast6_fu_270_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sum_i_fu_274_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_291_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_36_cast_fu_298_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_i_cast5_cast_fu_302_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_305_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond_i1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_328_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_31_fu_356_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_368_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_i5_mid2_fu_340_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_40_cast_fu_364_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_i5_cast1_cast_fu_384_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_fu_388_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i4_mid2_fu_372_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_i5_cast2_fu_380_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component dct_2d IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_block_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        in_block_ce0 : OUT STD_LOGIC;
        in_block_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        in_block_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        in_block_ce1 : OUT STD_LOGIC;
        in_block_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        out_block_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        out_block_ce0 : OUT STD_LOGIC;
        out_block_we0 : OUT STD_LOGIC;
        out_block_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_2d_col_inbuf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_2d_row_outbuf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    buf_2d_in_U : component dct_2d_col_inbuf
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_in_address0,
        ce0 => buf_2d_in_ce0,
        we0 => buf_2d_in_we0,
        d0 => input_r_q0,
        q0 => buf_2d_in_q0,
        address1 => grp_dct_2d_fu_196_in_block_address1,
        ce1 => buf_2d_in_ce1,
        q1 => buf_2d_in_q1);

    buf_2d_out_U : component dct_2d_row_outbuf
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_out_address0,
        ce0 => buf_2d_out_ce0,
        we0 => buf_2d_out_we0,
        d0 => grp_dct_2d_fu_196_out_block_d0,
        q0 => buf_2d_out_q0);

    grp_dct_2d_fu_196 : component dct_2d
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_2d_fu_196_ap_start,
        ap_done => grp_dct_2d_fu_196_ap_done,
        ap_idle => grp_dct_2d_fu_196_ap_idle,
        ap_ready => grp_dct_2d_fu_196_ap_ready,
        in_block_address0 => grp_dct_2d_fu_196_in_block_address0,
        in_block_ce0 => grp_dct_2d_fu_196_in_block_ce0,
        in_block_q0 => buf_2d_in_q0,
        in_block_address1 => grp_dct_2d_fu_196_in_block_address1,
        in_block_ce1 => grp_dct_2d_fu_196_in_block_ce1,
        in_block_q1 => buf_2d_in_q1,
        out_block_address0 => grp_dct_2d_fu_196_out_block_address0,
        out_block_ce0 => grp_dct_2d_fu_196_out_block_ce0,
        out_block_we0 => grp_dct_2d_fu_196_out_block_we0,
        out_block_d0 => grp_dct_2d_fu_196_out_block_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((exitcond_flatten_fu_218_p2 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_218_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                elsif ((((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0))) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and not((exitcond_flatten_fu_218_p2 = ap_const_lv1_0))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and not((ap_const_lv1_0 = exitcond_flatten2_fu_316_p2)))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_lv1_1 = ap_CS_fsm_state5) and not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done)))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_1;
                elsif ((((ap_const_lv1_1 = ap_CS_fsm_state5) and not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done))) or ((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and not((ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_dct_2d_fu_196_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_dct_2d_fu_196_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_state4))) then 
                    ap_reg_grp_dct_2d_fu_196_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_dct_2d_fu_196_ap_ready)) then 
                    ap_reg_grp_dct_2d_fu_196_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_i5_reg_185_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0) and (ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))) then 
                c_i5_reg_185 <= c_1_fu_405_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state5) and not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done)))) then 
                c_i5_reg_185 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    c_i_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_fu_218_p2 = ap_const_lv1_0))) then 
                c_i_reg_152 <= c_fu_285_p2;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                c_i_reg_152 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    indvar_flatten2_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0) and (ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))) then 
                indvar_flatten2_reg_163 <= indvar_flatten_next2_fu_322_p2;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state5) and not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done)))) then 
                indvar_flatten2_reg_163 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_fu_218_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_130 <= indvar_flatten_next_fu_224_p2;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                indvar_flatten_reg_130 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;

    r_i2_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_lv1_0 = exitcond_flatten2_reg_445))) then 
                r_i2_reg_174 <= r_i2_cast4_mid2_v_reg_454;
            elsif (((ap_const_lv1_1 = ap_CS_fsm_state5) and not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done)))) then 
                r_i2_reg_174 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    r_i_reg_141_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_415 = ap_const_lv1_0))) then 
                r_i_reg_141 <= r_i_cast8_mid2_v_reg_429;
            elsif (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then 
                r_i_reg_141 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_218_p2 = ap_const_lv1_0))) then
                c_i_mid2_reg_424 <= c_i_mid2_fu_242_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0))) then
                exitcond_flatten2_reg_445 <= exitcond_flatten2_fu_316_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0))) then
                exitcond_flatten_reg_415 <= exitcond_flatten_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0) and (ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))) then
                r_i2_cast4_mid2_v_reg_454 <= r_i2_cast4_mid2_v_fu_348_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (exitcond_flatten_fu_218_p2 = ap_const_lv1_0))) then
                r_i_cast8_mid2_v_reg_429 <= r_i_cast8_mid2_v_fu_250_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))) then
                sum3_i_reg_464 <= sum3_i_fu_399_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, exitcond_flatten_fu_218_p2, ap_enable_reg_pp0_iter0, exitcond_flatten2_fu_316_p2, ap_enable_reg_pp1_iter0, grp_dct_2d_fu_196_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not((exitcond_flatten_fu_218_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (not((ap_const_logic_0 = grp_dct_2d_fu_196_ap_done))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_logic_1 = ap_enable_reg_pp1_iter0) and not((ap_const_lv1_0 = exitcond_flatten2_fu_316_p2))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4 downto 4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3 downto 3);
    ap_CS_fsm_state8 <= ap_CS_fsm(5 downto 5);

    ap_done_assign_proc : process(ap_CS_fsm_state8)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state5, grp_dct_2d_fu_196_in_block_address0, tmp_38_cast_fu_311_p1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            buf_2d_in_address0 <= tmp_38_cast_fu_311_p1(6 - 1 downto 0);
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_in_address0 <= grp_dct_2d_fu_196_in_block_address0;
        else 
            buf_2d_in_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_in_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_state5, grp_dct_2d_fu_196_in_block_ce0)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then 
            buf_2d_in_ce0 <= ap_const_logic_1;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_in_ce0 <= grp_dct_2d_fu_196_in_block_ce0;
        else 
            buf_2d_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce1_assign_proc : process(ap_CS_fsm_state5, grp_dct_2d_fu_196_in_block_ce1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_in_ce1 <= grp_dct_2d_fu_196_in_block_ce1;
        else 
            buf_2d_in_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_we0_assign_proc : process(exitcond_flatten_reg_415, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_415 = ap_const_lv1_0)))) then 
            buf_2d_in_we0 <= ap_const_logic_1;
        else 
            buf_2d_in_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_address0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_CS_fsm_state5, grp_dct_2d_fu_196_out_block_address0, tmp_42_cast_fu_394_p1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0))) then 
            buf_2d_out_address0 <= tmp_42_cast_fu_394_p1(6 - 1 downto 0);
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_out_address0 <= grp_dct_2d_fu_196_out_block_address0;
        else 
            buf_2d_out_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_out_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_CS_fsm_state5, grp_dct_2d_fu_196_out_block_ce0)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0))) then 
            buf_2d_out_ce0 <= ap_const_logic_1;
        elsif (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_out_ce0 <= grp_dct_2d_fu_196_out_block_ce0;
        else 
            buf_2d_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_we0_assign_proc : process(ap_CS_fsm_state5, grp_dct_2d_fu_196_out_block_we0)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state5))) then 
            buf_2d_out_we0 <= grp_dct_2d_fu_196_out_block_we0;
        else 
            buf_2d_out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    c_1_fu_405_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(c_i5_mid2_fu_340_p3));
    c_fu_285_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(c_i_mid2_fu_242_p3));
    c_i5_cast1_cast_fu_384_p1 <= std_logic_vector(resize(unsigned(c_i5_mid2_fu_340_p3),8));
    c_i5_cast2_fu_380_p1 <= std_logic_vector(resize(unsigned(c_i5_mid2_fu_340_p3),6));
    c_i5_mid2_fu_340_p3 <= 
        ap_const_lv4_0 when (exitcond_i1_fu_334_p2(0) = '1') else 
        c_i5_reg_185;
    c_i_cast5_cast_fu_302_p1 <= std_logic_vector(resize(unsigned(c_i_mid2_reg_424),8));
    c_i_cast6_fu_270_p1 <= std_logic_vector(resize(unsigned(c_i_mid2_fu_242_p3),6));
    c_i_mid2_fu_242_p3 <= 
        ap_const_lv4_0 when (exitcond_i_fu_236_p2(0) = '1') else 
        c_i_reg_152;
    exitcond_flatten2_fu_316_p2 <= "1" when (indvar_flatten2_reg_163 = ap_const_lv7_40) else "0";
    exitcond_flatten_fu_218_p2 <= "1" when (indvar_flatten_reg_130 = ap_const_lv7_40) else "0";
    exitcond_i1_fu_334_p2 <= "1" when (c_i5_reg_185 = ap_const_lv4_8) else "0";
    exitcond_i_fu_236_p2 <= "1" when (c_i_reg_152 = ap_const_lv4_8) else "0";
    grp_dct_2d_fu_196_ap_start <= ap_reg_grp_dct_2d_fu_196_ap_start;
    indvar_flatten_next2_fu_322_p2 <= std_logic_vector(unsigned(indvar_flatten2_reg_163) + unsigned(ap_const_lv7_1));
    indvar_flatten_next_fu_224_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_130) + unsigned(ap_const_lv7_1));
    input_r_address0 <= sum_i_cast_fu_280_p1(6 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_address0 <= sum3_i_cast_fu_411_p1(6 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= buf_2d_out_q0;

    output_r_we0_assign_proc : process(exitcond_flatten2_reg_445, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1)
    begin
        if ((((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_lv1_0 = exitcond_flatten2_reg_445)))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    r_1_fu_328_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(r_i2_phi_fu_178_p4));
    r_fu_230_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(r_i_phi_fu_145_p4));
    r_i2_cast4_mid2_v_fu_348_p3 <= 
        r_1_fu_328_p2 when (exitcond_i1_fu_334_p2(0) = '1') else 
        r_i2_phi_fu_178_p4;

    r_i2_phi_fu_178_p4_assign_proc : process(r_i2_reg_174, exitcond_flatten2_reg_445, ap_CS_fsm_pp1_stage0, r_i2_cast4_mid2_v_reg_454, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_lv1_0 = exitcond_flatten2_reg_445))) then 
            r_i2_phi_fu_178_p4 <= r_i2_cast4_mid2_v_reg_454;
        else 
            r_i2_phi_fu_178_p4 <= r_i2_reg_174;
        end if; 
    end process;

    r_i_cast8_mid2_v_fu_250_p3 <= 
        r_fu_230_p2 when (exitcond_i_fu_236_p2(0) = '1') else 
        r_i_phi_fu_145_p4;

    r_i_phi_fu_145_p4_assign_proc : process(r_i_reg_141, exitcond_flatten_reg_415, ap_CS_fsm_pp0_stage0, r_i_cast8_mid2_v_reg_429, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_415 = ap_const_lv1_0))) then 
            r_i_phi_fu_145_p4 <= r_i_cast8_mid2_v_reg_429;
        else 
            r_i_phi_fu_145_p4 <= r_i_reg_141;
        end if; 
    end process;

    sum3_i_cast_fu_411_p1 <= std_logic_vector(resize(unsigned(sum3_i_reg_464),32));
    sum3_i_fu_399_p2 <= std_logic_vector(unsigned(tmp_i4_mid2_fu_372_p3) + unsigned(c_i5_cast2_fu_380_p1));
    sum_i_cast_fu_280_p1 <= std_logic_vector(resize(unsigned(sum_i_fu_274_p2),32));
    sum_i_fu_274_p2 <= std_logic_vector(unsigned(tmp_i_mid2_fu_262_p3) + unsigned(c_i_cast6_fu_270_p1));
    tmp_1_fu_258_p1 <= r_i_cast8_mid2_v_fu_250_p3(3 - 1 downto 0);
    tmp_2_fu_368_p1 <= r_i2_cast4_mid2_v_fu_348_p3(3 - 1 downto 0);
    tmp_31_fu_356_p3 <= (r_i2_cast4_mid2_v_fu_348_p3 & ap_const_lv3_0);
    tmp_32_fu_388_p2 <= std_logic_vector(unsigned(tmp_40_cast_fu_364_p1) + unsigned(c_i5_cast1_cast_fu_384_p1));
    tmp_36_cast_fu_298_p1 <= std_logic_vector(resize(unsigned(tmp_fu_291_p3),8));
    tmp_38_cast_fu_311_p1 <= std_logic_vector(resize(unsigned(tmp_s_fu_305_p2),32));
    tmp_40_cast_fu_364_p1 <= std_logic_vector(resize(unsigned(tmp_31_fu_356_p3),8));
    tmp_42_cast_fu_394_p1 <= std_logic_vector(resize(unsigned(tmp_32_fu_388_p2),32));
    tmp_fu_291_p3 <= (r_i_cast8_mid2_v_reg_429 & ap_const_lv3_0);
    tmp_i4_mid2_fu_372_p3 <= (tmp_2_fu_368_p1 & ap_const_lv3_0);
    tmp_i_mid2_fu_262_p3 <= (tmp_1_fu_258_p1 & ap_const_lv3_0);
    tmp_s_fu_305_p2 <= std_logic_vector(unsigned(tmp_36_cast_fu_298_p1) + unsigned(c_i_cast5_cast_fu_302_p1));
end behav;
