// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_Row_DCT_Loop_pr.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_Row_DCT_Loop_pr::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_Row_DCT_Loop_pr::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_ST_fsm_state1 = "1";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_ST_fsm_state2 = "10";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_ST_fsm_state8 = "1000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Loop_Row_DCT_Loop_pr::ap_const_lv1_1 = "1";
const bool Loop_Row_DCT_Loop_pr::ap_const_boolean_1 = true;
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_1 = "1";
const sc_lv<1> Loop_Row_DCT_Loop_pr::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_2 = "10";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_const_lv4_0 = "0000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_3 = "11";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_const_lv4_8 = "1000";
const sc_lv<4> Loop_Row_DCT_Loop_pr::ap_const_lv4_1 = "1";
const sc_lv<3> Loop_Row_DCT_Loop_pr::ap_const_lv3_0 = "000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_10 = "10000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_1F = "11111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_10 = "10000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_1F = "11111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_20 = "100000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_2F = "101111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_20 = "100000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_2F = "101111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_30 = "110000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_3F = "111111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_30 = "110000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_3F = "111111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_40 = "1000000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_4F = "1001111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_40 = "1000000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_4F = "1001111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_50 = "1010000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_5F = "1011111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_50 = "1010000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_5F = "1011111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_60 = "1100000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_6F = "1101111";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_60 = "1100000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_6F = "1101111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_70 = "1110000";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_7E = "1111110";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_70 = "1110000";
const sc_lv<9> Loop_Row_DCT_Loop_pr::ap_const_lv9_7F = "1111111";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_D = "1101";
const sc_lv<32> Loop_Row_DCT_Loop_pr::ap_const_lv32_1C = "11100";
const sc_lv<29> Loop_Row_DCT_Loop_pr::ap_const_lv29_1000 = "1000000000000";

Loop_Row_DCT_Loop_pr::Loop_Row_DCT_Loop_pr(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_U = new Loop_Row_DCT_Loopbkb("dct_coeff_table_U");
    dct_coeff_table_U->clk(ap_clk);
    dct_coeff_table_U->reset(ap_rst);
    dct_coeff_table_U->address0(dct_coeff_table_address0);
    dct_coeff_table_U->ce0(dct_coeff_table_ce0);
    dct_coeff_table_U->q0(dct_coeff_table_q0);
    dct_mul_mul_16s_1cud_U2 = new dct_mul_mul_16s_1cud<1,1,16,16,29>("dct_mul_mul_16s_1cud_U2");
    dct_mul_mul_16s_1cud_U2->din0(tmp_49_reg_542);
    dct_mul_mul_16s_1cud_U2->din1(tmp_50_reg_547);
    dct_mul_mul_16s_1cud_U2->dout(tmp_3_i_fu_446_p2);
    dct_mul_mul_16s_1cud_U3 = new dct_mul_mul_16s_1cud<1,1,16,16,29>("dct_mul_mul_16s_1cud_U3");
    dct_mul_mul_16s_1cud_U3->din0(tmp_8_i_reg_562);
    dct_mul_mul_16s_1cud_U3->din1(tmp_10_i_reg_567);
    dct_mul_mul_16s_1cud_U3->dout(tmp_3_2_i_fu_452_p2);
    dct_mul_mul_16s_1cud_U4 = new dct_mul_mul_16s_1cud<1,1,16,16,29>("dct_mul_mul_16s_1cud_U4");
    dct_mul_mul_16s_1cud_U4->din0(tmp_13_i_reg_582);
    dct_mul_mul_16s_1cud_U4->din1(tmp_14_i_reg_587);
    dct_mul_mul_16s_1cud_U4->dout(tmp_3_4_i_fu_458_p2);
    dct_mac_muladd_16dEe_U5 = new dct_mac_muladd_16dEe<1,1,16,16,29,29>("dct_mac_muladd_16dEe_U5");
    dct_mac_muladd_16dEe_U5->din0(tmp_17_i_reg_602);
    dct_mac_muladd_16dEe_U5->din1(tmp_18_i_reg_607);
    dct_mac_muladd_16dEe_U5->din2(grp_fu_471_p3);
    dct_mac_muladd_16dEe_U5->dout(grp_fu_464_p3);
    dct_mac_muladd_16eOg_U6 = new dct_mac_muladd_16eOg<1,1,16,15,14,29>("dct_mac_muladd_16eOg_U6");
    dct_mac_muladd_16eOg_U6->din0(tmp_20_i_reg_617);
    dct_mac_muladd_16eOg_U6->din1(tmp_1_reg_612);
    dct_mac_muladd_16eOg_U6->din2(grp_fu_471_p2);
    dct_mac_muladd_16eOg_U6->dout(grp_fu_471_p3);
    dct_mac_muladd_16dEe_U7 = new dct_mac_muladd_16dEe<1,1,16,16,29,29>("dct_mac_muladd_16dEe_U7");
    dct_mac_muladd_16dEe_U7->din0(ap_pipeline_reg_pp0_iter2_tmp_6_i_reg_552);
    dct_mac_muladd_16dEe_U7->din1(ap_pipeline_reg_pp0_iter2_tmp_7_i_reg_557);
    dct_mac_muladd_16dEe_U7->din2(tmp_3_i_reg_622);
    dct_mac_muladd_16dEe_U7->dout(grp_fu_480_p3);
    dct_mac_muladd_16dEe_U8 = new dct_mac_muladd_16dEe<1,1,16,16,29,29>("dct_mac_muladd_16dEe_U8");
    dct_mac_muladd_16dEe_U8->din0(ap_pipeline_reg_pp0_iter2_tmp_11_i_reg_572);
    dct_mac_muladd_16dEe_U8->din1(ap_pipeline_reg_pp0_iter2_tmp_12_i_reg_577);
    dct_mac_muladd_16dEe_U8->din2(tmp_3_2_i_reg_627);
    dct_mac_muladd_16dEe_U8->dout(grp_fu_488_p3);
    dct_mac_muladd_16dEe_U9 = new dct_mac_muladd_16dEe<1,1,16,16,29,29>("dct_mac_muladd_16dEe_U9");
    dct_mac_muladd_16dEe_U9->din0(ap_pipeline_reg_pp0_iter2_tmp_15_i_reg_592);
    dct_mac_muladd_16dEe_U9->din1(ap_pipeline_reg_pp0_iter2_tmp_16_i_reg_597);
    dct_mac_muladd_16dEe_U9->din2(tmp_3_4_i_reg_632);
    dct_mac_muladd_16dEe_U9->dout(grp_fu_496_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_fu_167_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_fu_167_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_buf_2d_in_address0);
    sensitive << ( buf_2d_in_addr_reg_518 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_buf_2d_in_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_dct_coeff_table_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( k_cast1_i_fu_208_p1 );

    SC_METHOD(thread_dct_coeff_table_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_471_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter1_tmp_i_reg_523 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_i_2_i1_cast_i_fu_179_p1);
    sensitive << ( i_0_i_reg_145 );

    SC_METHOD(thread_i_fu_173_p2);
    sensitive << ( i_0_i_reg_145 );

    SC_METHOD(thread_k_cast1_i_cast_fu_213_p1);
    sensitive << ( k_i_reg_156 );

    SC_METHOD(thread_k_cast1_i_fu_208_p1);
    sensitive << ( k_i_reg_156 );

    SC_METHOD(thread_k_fu_202_p2);
    sensitive << ( k_i_reg_156 );

    SC_METHOD(thread_row_outbuf_i_address0);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_17_cast_fu_442_p1 );

    SC_METHOD(thread_row_outbuf_i_ce0);
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_row_outbuf_i_d0);
    sensitive << ( tmp_1_i_reg_642 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_row_outbuf_i_we0);
    sensitive << ( ap_pipeline_reg_pp0_iter3_tmp_i_reg_523 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_tmp1_fu_418_p2);
    sensitive << ( grp_fu_488_p3 );
    sensitive << ( grp_fu_480_p3 );

    SC_METHOD(thread_tmp4_fu_422_p2);
    sensitive << ( tmp6_reg_637 );
    sensitive << ( grp_fu_496_p3 );

    SC_METHOD(thread_tmp_16_cast_fu_192_p1);
    sensitive << ( tmp_s_fu_184_p3 );

    SC_METHOD(thread_tmp_17_cast_fu_442_p1);
    sensitive << ( ap_pipeline_reg_pp0_iter3_tmp_4_reg_532 );

    SC_METHOD(thread_tmp_49_fu_222_p1);
    sensitive << ( dct_coeff_table_q0 );

    SC_METHOD(thread_tmp_4_fu_217_p2);
    sensitive << ( tmp_16_cast_reg_513 );
    sensitive << ( k_cast1_i_cast_fu_213_p1 );

    SC_METHOD(thread_tmp_50_fu_226_p1);
    sensitive << ( buf_2d_in_q0 );

    SC_METHOD(thread_tmp_9_i_fu_426_p2);
    sensitive << ( tmp4_fu_422_p2 );
    sensitive << ( tmp1_fu_418_p2 );

    SC_METHOD(thread_tmp_fu_167_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_reg_145 );

    SC_METHOD(thread_tmp_i_fu_196_p2);
    sensitive << ( k_i_reg_156 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_s_fu_184_p3);
    sensitive << ( i_0_i_reg_145 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_167_p2 );
    sensitive << ( tmp_i_fu_196_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_Row_DCT_Loop_pr_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, buf_2d_in_address0, "(port)buf_2d_in_address0");
    sc_trace(mVcdFile, buf_2d_in_ce0, "(port)buf_2d_in_ce0");
    sc_trace(mVcdFile, buf_2d_in_q0, "(port)buf_2d_in_q0");
    sc_trace(mVcdFile, row_outbuf_i_address0, "(port)row_outbuf_i_address0");
    sc_trace(mVcdFile, row_outbuf_i_ce0, "(port)row_outbuf_i_ce0");
    sc_trace(mVcdFile, row_outbuf_i_we0, "(port)row_outbuf_i_we0");
    sc_trace(mVcdFile, row_outbuf_i_d0, "(port)row_outbuf_i_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dct_coeff_table_address0, "dct_coeff_table_address0");
    sc_trace(mVcdFile, dct_coeff_table_ce0, "dct_coeff_table_ce0");
    sc_trace(mVcdFile, dct_coeff_table_q0, "dct_coeff_table_q0");
    sc_trace(mVcdFile, k_i_reg_156, "k_i_reg_156");
    sc_trace(mVcdFile, tmp_fu_167_p2, "tmp_fu_167_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_173_p2, "i_fu_173_p2");
    sc_trace(mVcdFile, i_reg_508, "i_reg_508");
    sc_trace(mVcdFile, tmp_16_cast_fu_192_p1, "tmp_16_cast_fu_192_p1");
    sc_trace(mVcdFile, tmp_16_cast_reg_513, "tmp_16_cast_reg_513");
    sc_trace(mVcdFile, buf_2d_in_addr_reg_518, "buf_2d_in_addr_reg_518");
    sc_trace(mVcdFile, tmp_i_fu_196_p2, "tmp_i_fu_196_p2");
    sc_trace(mVcdFile, tmp_i_reg_523, "tmp_i_reg_523");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_tmp_i_reg_523, "ap_pipeline_reg_pp0_iter1_tmp_i_reg_523");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_i_reg_523, "ap_pipeline_reg_pp0_iter2_tmp_i_reg_523");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_tmp_i_reg_523, "ap_pipeline_reg_pp0_iter3_tmp_i_reg_523");
    sc_trace(mVcdFile, k_fu_202_p2, "k_fu_202_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_4_fu_217_p2, "tmp_4_fu_217_p2");
    sc_trace(mVcdFile, tmp_4_reg_532, "tmp_4_reg_532");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_tmp_4_reg_532, "ap_pipeline_reg_pp0_iter1_tmp_4_reg_532");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_4_reg_532, "ap_pipeline_reg_pp0_iter2_tmp_4_reg_532");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_tmp_4_reg_532, "ap_pipeline_reg_pp0_iter3_tmp_4_reg_532");
    sc_trace(mVcdFile, tmp_49_fu_222_p1, "tmp_49_fu_222_p1");
    sc_trace(mVcdFile, tmp_49_reg_542, "tmp_49_reg_542");
    sc_trace(mVcdFile, tmp_50_fu_226_p1, "tmp_50_fu_226_p1");
    sc_trace(mVcdFile, tmp_50_reg_547, "tmp_50_reg_547");
    sc_trace(mVcdFile, tmp_6_i_reg_552, "tmp_6_i_reg_552");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_6_i_reg_552, "ap_pipeline_reg_pp0_iter2_tmp_6_i_reg_552");
    sc_trace(mVcdFile, tmp_7_i_reg_557, "tmp_7_i_reg_557");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_7_i_reg_557, "ap_pipeline_reg_pp0_iter2_tmp_7_i_reg_557");
    sc_trace(mVcdFile, tmp_8_i_reg_562, "tmp_8_i_reg_562");
    sc_trace(mVcdFile, tmp_10_i_reg_567, "tmp_10_i_reg_567");
    sc_trace(mVcdFile, tmp_11_i_reg_572, "tmp_11_i_reg_572");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_11_i_reg_572, "ap_pipeline_reg_pp0_iter2_tmp_11_i_reg_572");
    sc_trace(mVcdFile, tmp_12_i_reg_577, "tmp_12_i_reg_577");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_12_i_reg_577, "ap_pipeline_reg_pp0_iter2_tmp_12_i_reg_577");
    sc_trace(mVcdFile, tmp_13_i_reg_582, "tmp_13_i_reg_582");
    sc_trace(mVcdFile, tmp_14_i_reg_587, "tmp_14_i_reg_587");
    sc_trace(mVcdFile, tmp_15_i_reg_592, "tmp_15_i_reg_592");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_15_i_reg_592, "ap_pipeline_reg_pp0_iter2_tmp_15_i_reg_592");
    sc_trace(mVcdFile, tmp_16_i_reg_597, "tmp_16_i_reg_597");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_16_i_reg_597, "ap_pipeline_reg_pp0_iter2_tmp_16_i_reg_597");
    sc_trace(mVcdFile, tmp_17_i_reg_602, "tmp_17_i_reg_602");
    sc_trace(mVcdFile, tmp_18_i_reg_607, "tmp_18_i_reg_607");
    sc_trace(mVcdFile, tmp_1_reg_612, "tmp_1_reg_612");
    sc_trace(mVcdFile, tmp_20_i_reg_617, "tmp_20_i_reg_617");
    sc_trace(mVcdFile, tmp_3_i_fu_446_p2, "tmp_3_i_fu_446_p2");
    sc_trace(mVcdFile, tmp_3_i_reg_622, "tmp_3_i_reg_622");
    sc_trace(mVcdFile, tmp_3_2_i_fu_452_p2, "tmp_3_2_i_fu_452_p2");
    sc_trace(mVcdFile, tmp_3_2_i_reg_627, "tmp_3_2_i_reg_627");
    sc_trace(mVcdFile, tmp_3_4_i_fu_458_p2, "tmp_3_4_i_fu_458_p2");
    sc_trace(mVcdFile, tmp_3_4_i_reg_632, "tmp_3_4_i_reg_632");
    sc_trace(mVcdFile, grp_fu_464_p3, "grp_fu_464_p3");
    sc_trace(mVcdFile, tmp6_reg_637, "tmp6_reg_637");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, tmp_1_i_reg_642, "tmp_1_i_reg_642");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, i_0_i_reg_145, "i_0_i_reg_145");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_2_i1_cast_i_fu_179_p1, "i_2_i1_cast_i_fu_179_p1");
    sc_trace(mVcdFile, k_cast1_i_fu_208_p1, "k_cast1_i_fu_208_p1");
    sc_trace(mVcdFile, tmp_17_cast_fu_442_p1, "tmp_17_cast_fu_442_p1");
    sc_trace(mVcdFile, tmp_s_fu_184_p3, "tmp_s_fu_184_p3");
    sc_trace(mVcdFile, k_cast1_i_cast_fu_213_p1, "k_cast1_i_cast_fu_213_p1");
    sc_trace(mVcdFile, grp_fu_488_p3, "grp_fu_488_p3");
    sc_trace(mVcdFile, grp_fu_480_p3, "grp_fu_480_p3");
    sc_trace(mVcdFile, grp_fu_496_p3, "grp_fu_496_p3");
    sc_trace(mVcdFile, tmp4_fu_422_p2, "tmp4_fu_422_p2");
    sc_trace(mVcdFile, tmp1_fu_418_p2, "tmp1_fu_418_p2");
    sc_trace(mVcdFile, tmp_9_i_fu_426_p2, "tmp_9_i_fu_426_p2");
    sc_trace(mVcdFile, grp_fu_471_p3, "grp_fu_471_p3");
    sc_trace(mVcdFile, grp_fu_471_p2, "grp_fu_471_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Loop_Row_DCT_Loop_pr::~Loop_Row_DCT_Loop_pr() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_U;
    delete dct_mul_mul_16s_1cud_U2;
    delete dct_mul_mul_16s_1cud_U3;
    delete dct_mul_mul_16s_1cud_U4;
    delete dct_mac_muladd_16dEe_U5;
    delete dct_mac_muladd_16eOg_U6;
    delete dct_mac_muladd_16dEe_U7;
    delete dct_mac_muladd_16dEe_U8;
    delete dct_mac_muladd_16dEe_U9;
}

void Loop_Row_DCT_Loop_pr::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                    !esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                     esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read())))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        i_0_i_reg_145 = i_reg_508.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_i_reg_145 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()))) {
        k_i_reg_156 = k_fu_202_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
        k_i_reg_156 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()))) {
        ap_pipeline_reg_pp0_iter1_tmp_4_reg_532 = tmp_4_reg_532.read();
        ap_pipeline_reg_pp0_iter1_tmp_i_reg_523 = tmp_i_reg_523.read();
        tmp_i_reg_523 = tmp_i_fu_196_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        ap_pipeline_reg_pp0_iter2_tmp_11_i_reg_572 = tmp_11_i_reg_572.read();
        ap_pipeline_reg_pp0_iter2_tmp_12_i_reg_577 = tmp_12_i_reg_577.read();
        ap_pipeline_reg_pp0_iter2_tmp_15_i_reg_592 = tmp_15_i_reg_592.read();
        ap_pipeline_reg_pp0_iter2_tmp_16_i_reg_597 = tmp_16_i_reg_597.read();
        ap_pipeline_reg_pp0_iter2_tmp_4_reg_532 = ap_pipeline_reg_pp0_iter1_tmp_4_reg_532.read();
        ap_pipeline_reg_pp0_iter2_tmp_6_i_reg_552 = tmp_6_i_reg_552.read();
        ap_pipeline_reg_pp0_iter2_tmp_7_i_reg_557 = tmp_7_i_reg_557.read();
        ap_pipeline_reg_pp0_iter2_tmp_i_reg_523 = ap_pipeline_reg_pp0_iter1_tmp_i_reg_523.read();
        ap_pipeline_reg_pp0_iter3_tmp_4_reg_532 = ap_pipeline_reg_pp0_iter2_tmp_4_reg_532.read();
        ap_pipeline_reg_pp0_iter3_tmp_i_reg_523 = ap_pipeline_reg_pp0_iter2_tmp_i_reg_523.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
        buf_2d_in_addr_reg_518 =  (sc_lv<3>) (i_2_i1_cast_i_fu_179_p1.read());
        tmp_16_cast_reg_513 = tmp_16_cast_fu_192_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        i_reg_508 = i_fu_173_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_pipeline_reg_pp0_iter1_tmp_i_reg_523.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        tmp6_reg_637 = grp_fu_464_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_reg_523.read()))) {
        tmp_10_i_reg_567 = buf_2d_in_q0.read().range(47, 32);
        tmp_11_i_reg_572 = dct_coeff_table_q0.read().range(63, 48);
        tmp_12_i_reg_577 = buf_2d_in_q0.read().range(63, 48);
        tmp_13_i_reg_582 = dct_coeff_table_q0.read().range(79, 64);
        tmp_14_i_reg_587 = buf_2d_in_q0.read().range(79, 64);
        tmp_15_i_reg_592 = dct_coeff_table_q0.read().range(95, 80);
        tmp_16_i_reg_597 = buf_2d_in_q0.read().range(95, 80);
        tmp_17_i_reg_602 = dct_coeff_table_q0.read().range(111, 96);
        tmp_18_i_reg_607 = buf_2d_in_q0.read().range(111, 96);
        tmp_1_reg_612 = dct_coeff_table_q0.read().range(126, 112);
        tmp_20_i_reg_617 = buf_2d_in_q0.read().range(127, 112);
        tmp_49_reg_542 = tmp_49_fu_222_p1.read();
        tmp_50_reg_547 = tmp_50_fu_226_p1.read();
        tmp_6_i_reg_552 = dct_coeff_table_q0.read().range(31, 16);
        tmp_7_i_reg_557 = buf_2d_in_q0.read().range(31, 16);
        tmp_8_i_reg_562 = dct_coeff_table_q0.read().range(47, 32);
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_pipeline_reg_pp0_iter2_tmp_i_reg_523.read())) {
        tmp_1_i_reg_642 = tmp_9_i_fu_426_p2.read().range(28, 13);
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_pipeline_reg_pp0_iter1_tmp_i_reg_523.read())) {
        tmp_3_2_i_reg_627 = tmp_3_2_i_fu_452_p2.read();
        tmp_3_4_i_reg_632 = tmp_3_4_i_fu_458_p2.read();
        tmp_3_i_reg_622 = tmp_3_i_fu_446_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()))) {
        tmp_4_reg_532 = tmp_4_fu_217_p2.read();
    }
}

void Loop_Row_DCT_Loop_pr::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(2, 2);
}

void Loop_Row_DCT_Loop_pr::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void Loop_Row_DCT_Loop_pr::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void Loop_Row_DCT_Loop_pr::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(3, 3);
}

void Loop_Row_DCT_Loop_pr::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          !esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_buf_2d_in_address0() {
    buf_2d_in_address0 = buf_2d_in_addr_reg_518.read();
}

void Loop_Row_DCT_Loop_pr::thread_buf_2d_in_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        buf_2d_in_ce0 = ap_const_logic_1;
    } else {
        buf_2d_in_ce0 = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_dct_coeff_table_address0() {
    dct_coeff_table_address0 =  (sc_lv<3>) (k_cast1_i_fu_208_p1.read());
}

void Loop_Row_DCT_Loop_pr::thread_dct_coeff_table_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        dct_coeff_table_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_ce0 = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_grp_fu_471_p2() {
    grp_fu_471_p2 =  (sc_lv<14>) (ap_const_lv29_1000);
}

void Loop_Row_DCT_Loop_pr::thread_i_2_i1_cast_i_fu_179_p1() {
    i_2_i1_cast_i_fu_179_p1 = esl_zext<32,4>(i_0_i_reg_145.read());
}

void Loop_Row_DCT_Loop_pr::thread_i_fu_173_p2() {
    i_fu_173_p2 = (!i_0_i_reg_145.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_i_reg_145.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Loop_Row_DCT_Loop_pr::thread_k_cast1_i_cast_fu_213_p1() {
    k_cast1_i_cast_fu_213_p1 = esl_zext<8,4>(k_i_reg_156.read());
}

void Loop_Row_DCT_Loop_pr::thread_k_cast1_i_fu_208_p1() {
    k_cast1_i_fu_208_p1 = esl_zext<32,4>(k_i_reg_156.read());
}

void Loop_Row_DCT_Loop_pr::thread_k_fu_202_p2() {
    k_fu_202_p2 = (!k_i_reg_156.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_i_reg_156.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Loop_Row_DCT_Loop_pr::thread_row_outbuf_i_address0() {
    row_outbuf_i_address0 =  (sc_lv<6>) (tmp_17_cast_fu_442_p1.read());
}

void Loop_Row_DCT_Loop_pr::thread_row_outbuf_i_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())) {
        row_outbuf_i_ce0 = ap_const_logic_1;
    } else {
        row_outbuf_i_ce0 = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_row_outbuf_i_d0() {
    row_outbuf_i_d0 = tmp_1_i_reg_642.read();
}

void Loop_Row_DCT_Loop_pr::thread_row_outbuf_i_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_pipeline_reg_pp0_iter3_tmp_i_reg_523.read())))) {
        row_outbuf_i_we0 = ap_const_logic_1;
    } else {
        row_outbuf_i_we0 = ap_const_logic_0;
    }
}

void Loop_Row_DCT_Loop_pr::thread_tmp1_fu_418_p2() {
    tmp1_fu_418_p2 = (!grp_fu_488_p3.read().is_01() || !grp_fu_480_p3.read().is_01())? sc_lv<29>(): (sc_bigint<29>(grp_fu_488_p3.read()) + sc_bigint<29>(grp_fu_480_p3.read()));
}

void Loop_Row_DCT_Loop_pr::thread_tmp4_fu_422_p2() {
    tmp4_fu_422_p2 = (!tmp6_reg_637.read().is_01() || !grp_fu_496_p3.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp6_reg_637.read()) + sc_bigint<29>(grp_fu_496_p3.read()));
}

void Loop_Row_DCT_Loop_pr::thread_tmp_16_cast_fu_192_p1() {
    tmp_16_cast_fu_192_p1 = esl_zext<8,7>(tmp_s_fu_184_p3.read());
}

void Loop_Row_DCT_Loop_pr::thread_tmp_17_cast_fu_442_p1() {
    tmp_17_cast_fu_442_p1 = esl_zext<32,8>(ap_pipeline_reg_pp0_iter3_tmp_4_reg_532.read());
}

void Loop_Row_DCT_Loop_pr::thread_tmp_49_fu_222_p1() {
    tmp_49_fu_222_p1 = dct_coeff_table_q0.read().range(16-1, 0);
}

void Loop_Row_DCT_Loop_pr::thread_tmp_4_fu_217_p2() {
    tmp_4_fu_217_p2 = (!k_cast1_i_cast_fu_213_p1.read().is_01() || !tmp_16_cast_reg_513.read().is_01())? sc_lv<8>(): (sc_biguint<8>(k_cast1_i_cast_fu_213_p1.read()) + sc_biguint<8>(tmp_16_cast_reg_513.read()));
}

void Loop_Row_DCT_Loop_pr::thread_tmp_50_fu_226_p1() {
    tmp_50_fu_226_p1 = buf_2d_in_q0.read().range(16-1, 0);
}

void Loop_Row_DCT_Loop_pr::thread_tmp_9_i_fu_426_p2() {
    tmp_9_i_fu_426_p2 = (!tmp4_fu_422_p2.read().is_01() || !tmp1_fu_418_p2.read().is_01())? sc_lv<29>(): (sc_biguint<29>(tmp4_fu_422_p2.read()) + sc_biguint<29>(tmp1_fu_418_p2.read()));
}

void Loop_Row_DCT_Loop_pr::thread_tmp_fu_167_p2() {
    tmp_fu_167_p2 = (!i_0_i_reg_145.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_145.read() == ap_const_lv4_8);
}

void Loop_Row_DCT_Loop_pr::thread_tmp_i_fu_196_p2() {
    tmp_i_fu_196_p2 = (!k_i_reg_156.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_i_reg_156.read() == ap_const_lv4_8);
}

void Loop_Row_DCT_Loop_pr::thread_tmp_s_fu_184_p3() {
    tmp_s_fu_184_p3 = esl_concat<4,3>(i_0_i_reg_145.read(), ap_const_lv3_0);
}

void Loop_Row_DCT_Loop_pr::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(tmp_fu_167_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_196_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

